### ISSUE TITLE
Add Support for CJK Languages

### ISSUE THREAD

**Issue by Liechti** [scrapinghub/dateparser#10]
Hi,

I'm working on adding support for parsing CJK (Chinese, Japanese, Korean) languages and had a few questions.

I have defined a `zh_parserinfo` class and have been able to get a test case like this to work:

    def test_zh_dates(self):
        date = DateParser(language='zh').parse(u'2014年10月4日', date_format='%Y年%m月%d日')   
        self.assertEqual(date.year, 2014)
        self.assertEqual(date.month, 10)
        self.assertEqual(date.day, 4)

However, this is not ideal. Dates are always written year-month-day, so it would be nice if `parse` handled it by default, and the above test case would pass without specifying this `date_format`. There are also two cases to support:

    # 年 means year, 月 means month, 日 means day
    # Dates are always written year first.
    date = DateParser(language='zh').parse(u'2014年10月4日')   
    
    # This is the same date, but it is written with Chinese numbers. 
    # 二 = 2, 〇 = 0, 一 = 1, 四 =  4, 十 = 10, etc...
    date = DateParser(language='zh').parse(u'二〇一四年十月四日')  # formal usage

Where would you suggest putting the code to handle the mapping of Chinese numbers to standard numbers? Any another suggestions for implementing this are appreciated. Thanks!
  
Edit: I'm not familiar with Arabic, but in #6 it looks like a similar mapping is needed. Something generic that could work for CJK languages, Arabic, and whatever other languages might need this would be best.

**Comment by waqasshabbir** [comment]
Hi @Liechti dateparser has changed a lot since this issue was opened. I'd encourage you to try it for chinese and japanese again. We do not support korean as of now. Please feel free to make any contributions. Thanks!
