### ISSUE TITLE
Exception with tzlocal

### ISSUE THREAD

**Issue by ciakkarino** [scrapinghub/dateparser#1001]
The tzlocal pip package was just updated to the version 4.0.
It seesm that in this version you should define explicitely your timezone, if not it raise an exception like

`tzlocal.utils.ZoneInfoNotFoundError: 'Multiple conflicting time zone configurations found`

**Comment by Gallaecio** [comment]
@ciakkarino @flaviussn [Is this still a problem?](https://github.com/zytedata/majornetlocs/).

And, if it is, could any of you provide the shortest possible Python code to reproduce this issue? It is not clear to me if, when you say you should specify your timezone, you mean at the ssytem level or something else.

**Comment by ciakkarino** [comment]
Hi Gallaecio, I installed the latest version of dateparser and tzlocal and now everything works fine.
So it's not anymore a problem :)
