### ISSUE TITLE
Comparing dateparser to parsedatetime?

### ISSUE THREAD

**Issue by BjornFJohansson** [scrapinghub/dateparser#1019]
Hi, there is a library called "bear/parsedatetime" that seem to have comparable goals. What would 
be some reasons to choose one over the other?

**Comment by lopuhin** [comment]
hi @BjornFJohansson thanks for the link :+1: I think both libraries have very similar goals, so it's probably mostly question of quality, which someone needs to measure.
One thing I noticed is that the number of supported languages is smaller for parsedatetime: https://github.com/bear/parsedatetime/tree/master/parsedatetime/pdt_locales vs https://github.com/scrapinghub/dateparser/tree/master/dateparser/data/date_translation_data
