### ISSUE TITLE
PytzUsageWarning: The localize method is no longer necessary

### ISSUE THREAD

**Issue by atompie** [scrapinghub/dateparser#1025]
When parsing date.

PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  date_obj = stz.localize(date_obj)

**Comment by neon-ninja** [comment]
Duplicate of https://github.com/scrapinghub/dateparser/issues/1013

**Comment by lopuhin** [comment]
Closing as a duplicate of #1013, thanks @neon-ninja
