### ISSUE TITLE
dateparder.parse() returns None for any case

### ISSUE THREAD

**Issue by Altimis** [scrapinghub/dateparser#1054]
Example of code :  
input : ``print(dateparser.parse('12/12/12'))``  
output :  ``None``

**Comment by 0xDEC0DE** [comment]
I cannot reproduce this.  Using version 1.1.1 on Mac OS X:

```python
>>> import dateparser
>>> dateparser.__version__
'1.1.1'
>>> dateparser.parse('12/12/12')
datetime.datetime(2012, 12, 12, 0, 0)
>>> print(dateparser.parse('12/12/12'))
2012-12-12 00:00:00
```

Please provide more detail (package version, platform, etc.)

**Comment by Altimis** [comment]
Actually I fixed it by using settings argument :  
``dateparser.parse("12/12/12", settings="UTC/")``
