### ISSUE TITLE
Improper parsing of relative date with absolute time of exactly midnight

### ISSUE THREAD

**Issue by rcwxok** [scrapinghub/dateparser#107]
When parsing a relative date with an absolute time (e.g., 1 week ago at 12 am), the parser ignores the time portion if it is exactly midnight (00:00:00 or the equivalent). If the time portion is one minute later, it works properly. This is with Python 2.7.9 and dateparser 0.3.0. Thanks.

In [1]: import dateparser as dp

In [2]: dp.parse('1 week ago at 12:00 am')
Out[2]: datetime.datetime(2015, 8, 24, 18, 35, 6, 272800)

In [3]: dp.parse('1 week ago at 12:01 am')
Out[3]: datetime.datetime(2015, 8, 24, 0, 1)

**Comment by waqasshabbir** [comment]
Hi @rcwxok, thank you so much for your interest in dateparser and reporting this bug. A fix is proposed here: PR #115

**Comment by waqasshabbir** [comment]
Fixed in #115
