### ISSUE TITLE
"in 5 min" returns None

### ISSUE THREAD

**Issue by prat0088** [scrapinghub/dateparser#109]
I just downloaded this module and it's fantastic.  Thank you for it.

I noticed that "5 min ago" works.  "in 5 min" returns None.

**Comment by waqasshabbir** [comment]
Hi @prat0088 we're glad that you liked it and found it useful. This one and #111 are similar. Dateparser doesn't support future dates as of now but we do have plans for them in future.

**Comment by waqasshabbir** [comment]
Fixed in #137
