### ISSUE TITLE
Formating with given locale

### ISSUE THREAD

**Issue by barslmn** [scrapinghub/dateparser#1106]
Hi,
This might be out of scope for this library. 

Is there a way to format the date in given locale or do we use the builtin `datetime` and `locale` libraries? 

For instance I parse the "date" _A2M_ in Spanish, Is there a way to print the month and dates as Spanish? 
```
>>> DateDataParser(languages=['es'], settings={'STRICT_PARSING':True}).get_date_data('A2M').date_obj.strftime('%A %B %X %x')
'Wednesday September 14:44:14 09/28/22'
```

**Comment by Gallaecio** [comment]
Serialization is indeed out of the scope of dateparser, which focuses on the parsing part. For serializing, you can indeed use `datetime`, or non-standard libraries like https://github.com/timofurrer/maya.

**Comment by barslmn** [comment]
I am avoiding stdlib since it uses the system locale. And installing all the locales to system might cause problems maybe. Thanks for pointing out maya.
