### ISSUE TITLE
can't parse 'Mon, 12 Dec 2022 10:07:48 +0000'

### ISSUE THREAD

**Issue by 0xDEADFED5** [scrapinghub/dateparser#1120]
unable to parse strings like the following:
`Mon, 12 Dec 2022 10:07:48 +0000`
if I remove the 'Mon, ' part, like using the following regex, then it works:
`foo = re.sub('^\\w+, ', '', foo)`

**Comment by asadurski** [comment]
Thank you. Already reported in https://github.com/scrapinghub/dateparser/issues/1116.
Please follow that issue.
