### ISSUE TITLE
Full warning

### ISSUE THREAD

**Issue by NandhakumarSL** [scrapinghub/dateparser#1165]
/lib/python3.10/site-packages/dateparser/date_parser.py:35: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  date_obj = stz.localize(date_obj)

**Comment by Gallaecio** [comment]
https://github.com/scrapinghub/dateparser/issues/1089
