### ISSUE TITLE
Returning ambiguous naive datetimes when tz info is available

### ISSUE THREAD

**Issue by akoumjian** [scrapinghub/dateparser#143]
Originally this was a bit more confusing because dateparser returned both a naive datetime object while also converting it using the local timezone offset. This was updated in 3.2, but I would still make the case that it makes more sense to return the datetime object with timezone data attached, when possible.

See this writeup that @thebigspoon put together: 

https://gist.github.com/thebigspoon/a5e38d029577fe9ddb94

**Comment by asadurski** [comment]
Would it be enough to select timezone aware output in settings (not make it default - for now)?

**Comment by thebigspoon** [comment]
@asadurski 
If i understand correctly, yes, a setting option like `RETURN_AS_TIMEZONE_AWARE` would be enough:
```python
>>> parse('01-12-2012 EST', settings={
    "RETURN_AS_TIMEZONE_AWARE": True, 
    "TIMEZONE": "EST"
})
datetime.datetime(2012, 1, 12, 0, 0, tzinfo=<StaticTzInfo 'EST'>)
```

**Comment by waqasshabbir** [comment]
Hi @thebigspoon and @akoumjian, please take a look into the referenced PR and let us know what you think about it. Thanks!
