### ISSUE TITLE
UnicodeDecodeError caused by setup.py on Python 3

### ISSUE THREAD

**Issue by buckket** [scrapinghub/dateparser#151]
When installing `dateparser` on a system which has no or non-utf8 locale variables set (e.g. RTD’s servers), installation fails because you’re making use of the `open()` command in `setup.py` to read things like `README.rst` and `HISTORY.rst`. This happens because Python 3 tries loading those files with the default encoding (which happens to be ASCII), and then fails with an `UnicodeDecodeError`.

You could use `io.open()`, which is available for both Python 2 and 3 and specify the encoding of said files explicitly.

One could argue that this problem is client-sided, but I don’t see any real drawbacks fixing this on your side.

Thanks.

**Comment by waqasshabbir** [comment]
Fixed by PR #176
