### ISSUE TITLE
python-dateutil Upgrade to >2.5 breaks dateparser.parse

### ISSUE THREAD

**Issue by dvetal** [scrapinghub/dateparser#154]
My team was recently successfully using dateparser.parse on our project.  Once the python-dateutil package upgraded from 2.4.2 to 2.5.0  dateparser.parse no longer worked.  We received the following error:
AttributeError: 'tuple' object has no attribute 'year'

To reproduce the error pin python-dateutil to 2.5.0 in your environment and run dateparser.parse with a reasonable datatime string.

We're pinning python-dateutil to 2.4.2 but thought you should know.

**Comment by waqasshabbir** [comment]
Thank you for the heads up @dvetal! we were aware of this issue and fixed that already in release 0.3.4. https://github.com/scrapinghub/dateparser/blob/master/HISTORY.rst
