### ISSUE TITLE
dateparser-0.3.4 incompatible with python-dateutil-2.5.3: 'tuple' object has no attribute '__slots__'

### ISSUE THREAD

**Issue by benjaminvdb** [scrapinghub/dateparser#173]
### Description
If I install dateparser through pip, python-dateutil-2.4.2 gets pulled as a dependency and all works fine. However, I frequently update my packages (blindly, I must say) and sometimes other packages require a more recent version. In this case, an update pulled in python-dateutil-2.5.3, which broke dateparser. The cause of the problem was quite hard to find.

The error I get is: `AttributeError: 'tuple' object has no attribute '__slots__'`. A full tracelog is attached with this Issue.

### Reproduce the bug
`pip install dateparser ()`
`pip install --upgrade python-dateutil`

This pulls python-dateutil-2.5.3 at the moment.

### Workaround
`pip uninstall python-dateutil`
`pip install dateparser`

This pulls python-dateutil-2.4.2 at the moment.

### Tracelog
[python-dateutil.log.zip](https://github.com/scrapinghub/dateparser/files/229798/python-dateutil.log.zip)

**Comment by waqasshabbir** [comment]
Hi @benjaminvdb the issue is already solved by PR #165 and will be fixed in the upcoming release which is due soon.

Hope this helps! Thank you!

**Comment by benjaminvdb** [comment]
@waqasshabbir Alright, that's great! I assumed the patch was already committed to the repo, so I installed dateparser from there and it works just fine with python-dateutil-2.5.3. Thanks a lot!

To install the latest development release of dateparser from GitHub with pip:

`pip install --upgrade git+https://github.com/scrapinghub/dateparser.git`

dateparser is a wonderful tool. Keep up the good work! 👍
