### ISSUE TITLE
'PREFER_DATES_FROM'='past' returns future date when a past one is available

### ISSUE THREAD

**Issue by adamn** [scrapinghub/dateparser#175]
If I pass in '9/2/16' to parse() and want a date in the past, I should get `datetime.datetime(2016, 2, 9, 0, 0)
` if the current date is before September 2, 2016.  parse() currently just returns the future date anyway.

```python
>>> datetime.datetime.now()
datetime.datetime(2016, 5, 5, 16, 27, 38, 227337)
>>> dateparser.parse('9/2/16', settings={'PREFER_DATES_FROM': 'past'})
datetime.datetime(2016, 9, 2, 0, 0)
```

**Comment by waqasshabbir** [comment]
Hi @adamn, the setting for date preference for future or past is applicable to incomplete dates. Take a look at the examples below:

```
In [3]: parse('23 November')
Out[3]: datetime.datetime(2016, 11, 23, 0, 0)

In [4]: parse('23 November', settings={'PREFER_DATES_FROM': 'past'})
Out[4]: datetime.datetime(2015, 11, 23, 0, 0)

In [5]: parse('Saturday')
Out[5]: datetime.datetime(2016, 4, 30, 0, 0)

In [6]: parse('Saturday', settings={'PREFER_DATES_FROM': 'future'})
Out[5]: datetime.datetime(2016, 5, 7, 0, 0)
```

In your sample, the date is complete and the issue is with ordering where day comes first. You can fix this issue by specifying a date format:

```
In [8]: parse('9/2/16')
Out[8]: datetime.datetime(2016, 9, 2, 0, 0)

In [9]: parse('9/2/16', date_formats=['%d/%m/%y'])
Out[9]: datetime.datetime(2016, 2, 9, 0, 0)
```

**Comment by adamn** [comment]
Thanks for the detailed reply.  It would be nice to have the 'future' or 'past' attributes handle complete dates too - and it doesn't seem like it would hurt any current usecases.  In my case I don't know if the date is d/m/y or m/d/y so I would need a number of if statements to do the logic above.  

Alternatively, if parse() (or a new method) could return the format it used when determining the date, that would allow me to have simplified logic.
