### ISSUE TITLE
Overriding default global settings

### ISSUE THREAD

**Issue by richardxia** [scrapinghub/dateparser#184]
I was wondering if there's an official way of overriding the default global settings. It seems like it's possible to do by directly setting a value on `dateparser.conf.settings`, like so:

```python
import dateparser
dateparser.conf.settings.RETURN_AS_TIMEZONE_AWARE = True
```

For my particular use case, I'd like for `dateparser` to always return timezone-aware datetimes, and it's a bit of a hassle to always pass in the setting to every call to `dateparser.parse()`. If my code snippet above is the preferred way of overriding default settings, I'd be more than happy to write up some documentation for it.

**Comment by waqasshabbir** [comment]
You can create a `DateDataParser` instance for specific settings and use that instance to parse dates without having to pass settings each time like below.

```
In [1]: from dateparser.date import DateDataParser
dd
In [2]: ddp = DateDataParser(settings={'RETURN_AS_TIMEZONE_AWARE': True, 'TIMEZONE': None})

In [3]: ddp.get_date_data('12 April 2015 10:15 EST')
Out[3]:
{'date_obj': datetime.datetime(2015, 4, 12, 10, 15, tzinfo=<StaticTzInfo 'EST'>),
 'period': u'day'}

In [4]: ddp.get_date_data('12 April 2015 10:15 EDT')
Out[4]:
{'date_obj': datetime.datetime(2015, 4, 12, 10, 15, tzinfo=<StaticTzInfo 'EDT'>),
 'period': u'day'}

In [5]: ddp.get_date_data('12 April 2015 10:15 PDT')
Out[5]:
{'date_obj': datetime.datetime(2015, 4, 12, 10, 15, tzinfo=<StaticTzInfo 'PDT'>),
 'period': u'day'}
```

**Comment by richardxia** [comment]
Thanks, that's helpful, but it still only allows me to set settings on a per-module basis, and it has a slightly different and clunkier return value. It'd be great if there were a solution that allowed me to use the `parse()` function with default values.

**Comment by waqasshabbir** [comment]
Sure, if some users want different defaults across all the modules in the package without using `DateDataParser()`, your snippet in the question is the way to go, although, it's not the preferred way. `parse()` and `DateDataParser.get_date_data()` are the gateways to the entire functionality encapsulated by `dateparser`. Passing settings alongwith them equates the aforementioned behavior in a more organized way.
