### ISSUE TITLE
Unexpected result when parsing e.g "3.0 weeks ago"

### ISSUE THREAD

**Issue by blha303** [scrapinghub/dateparser#188]
>>> dateparser.parse("3.0 weeks ago")
    datetime.datetime(2016, 6, 12, 0, 0) # now
    >>> dateparser.parse("3 weeks ago")
    datetime.datetime(2016, 5, 22, 9, 18, 4, 289633) # correct result

Do I need to fix the input before using dateparser or is this a bug? 

dateparser-0.3.5, Python 3.5.1, Arch Linux 4.5.4-1-ARCH

**Comment by waqasshabbir** [comment]
@blha303 I'm not sure if fractional relative dates are very common. Looks like a corner case to me and should be taken care of at input level. Thanks for reporting though!
