### ISSUE TITLE
Parsing a stringified Python date doesn't work anymore

### ISSUE THREAD

**Issue by eliasdorneles** [scrapinghub/dateparser#198]
Hey folks!

This used to work, right?

```
$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> import dateparser
>>> dateparser.__version__
'0.4.0'
>>> datetime.datetime.now()
datetime.datetime(2016, 6, 21, 10, 10, 2, 214991)
>>> str(datetime.datetime.now())
'2016-06-21 10:10:05.626942'
>>> dateparser.parse(str(datetime.datetime.now()))
>>>  # expected a datetime object, but it returned None
```

I tried to use an old script (I can't remember which version I was using at the time) that relied on this, but this doesn't working with the newest version.

**Comment by adamn** [comment]
This works on 0.3.5:

```python
Python 3.5.1 (default, Dec 18 2015, 00:00:00)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import datetime
>>> import dateparser
>>> dateparser.__version__
'0.3.5'
>>> str(datetime.datetime.now())
'2016-06-22 15:47:06.267928'
>>> dateparser.parse(str(datetime.datetime.now()))
datetime.datetime(2016, 6, 22, 15, 47, 14, 964083)
>>>
```

Is this related to "Replaced dateutil.parser.parse with dateparser's own parser." introduced in 0.4.0?  #187 seems like a huge change ... that really should have been done upstream as suggested in the ticket.

**Comment by waqasshabbir** [comment]
@adamn yes it was related to the changes in PR #187. The reason why I didn't choose to do the upstream was new parser is designed around use cases handled by dateparser with little consideration for extensibility and is tightly coupled with customizable configurations (i.e. `dateparser.conf.settings`). It would have taken more work to make it suitable for dateutil given it has a slightly different approach planned for future to overhaul its parser.
