### ISSUE TITLE
Incorrect date parsing.

### ISSUE THREAD

**Issue by shmuga** [scrapinghub/dateparser#208]
Hello.
I have found some strange date parsing.
Version of dateparser **0.3.5**
Code sample:
```python
print dateparser.parse("27.08")
// prints 2016-07-27 00:00:00
```
And same problem I have using default `dateutil.parser`. Is this bug fixed in newer version of lib?

**Comment by waqasshabbir** [comment]
@shmuga yes looks like it.

```
In [1]: import dateparser; dateparser.parse('27.08')
Out[1]: datetime.datetime(2016, 8, 27, 0, 0)
```
