### ISSUE TITLE
Timezone confusion (mine)

### ISSUE THREAD

**Issue by brechmos** [scrapinghub/dateparser#212]
The package looks great. I am very excited to use it. 

But I am confused by something, if I do:
```
>>> dt = dateparser.parse('2pm', settings={'TIMEZONE': 'US/Eastern', 'RETURN_AS_TIMEZONE_AWARE': True})
```
the output is 
```
datetime.datetime(2016, 7, 22, 10, 0, tzinfo=<DstTzInfo 'US/Eastern' EDT-1 day, 20:00:00 DST>)
```
but I would have thought it should be 14 for the hour as the timezone is the correct one. 

I am confused.

**Comment by pganssle** [comment]
@brechmos I'm not super familiar with the library, but it looks to me like like it's interpreting `'2pm'` as 2PM UTC, then converting it to EST.

Looks like [this](https://github.com/scrapinghub/dateparser/blob/master/dateparser/utils/__init__.py#L108) is the problem. Essentially, `dateparser` assumes that all dates with unspecified timezones are UTC. It seems to me that unspecified should be unspecified.

**Comment by brechmos** [comment]
Thanks for confirming... I was thinking the settings TIMEZONE US/Eastern meant that it would be interpreted as the time zone.

**Comment by brechmos** [comment]
Just FYI, I made some tweaks and created a pull request #214 based on @pganssle (thanks!) finding the location of where it appears to be assuming the UTC timezone.

**Comment by waqasshabbir** [comment]
I agree `TIMEZONE` setting is confusing. Even the docs are not obvious enough. I'll push a fix soon.  Thanks @brechmos @pganssle!
