### ISSUE TITLE
Adding date formats

### ISSUE THREAD

**Issue by Jwink3101** [scrapinghub/dateparser#215]
I am not sure how the code actually works, but it would be great to be able to specify additional formats. For example, I often use the formats:
 
* `2016-07-28_090707` 
* `2016-07-28_090707_n0700` (where I use `n` for `-` even though `-` is an acceptable character, the opposite `+` isn't always)
* `2016-07-28_090707_p0700`

I do not know if you plan to make it easy to extend the formats. Personally, I am first attempting to parse with my own attempts and using `dateparser` as a fallback.

**Comment by waqasshabbir** [comment]
hi @Jwink310, thank you for your interest in date parser! I believe we already have support for something similar. You can pass a list of formats to `parse` function using `date_formats` keyword argument, that will make dateparser attempt to parse the date using the supplied format first. For more info, please look at the docs here: https://dateparser.readthedocs.io/en/latest/#dateparser.parse
