### ISSUE TITLE
Can't parse abbreviated 'Tues' in date

### ISSUE THREAD

**Issue by torymur** [scrapinghub/dateparser#216]
I'm not sure is this module suppose to support such kinds of abbreviations, but for the sake of the history will leave it here.

```
In [10]: dateparser.parse('Tue 9th Aug')
Out[10]: datetime.datetime(2016, 8, 9, 0, 0)

In [11]: dateparser.parse('Tues 9th Aug')
```

**Comment by hakanw** [comment]
I just encountered this bug also. "Tues" seems to be used 'in the wild' sometimes.

**Comment by hakanw** [comment]
Thanks @waqasshabbir !
