### ISSUE TITLE
We need support for 'Today 01:56 AM'

### ISSUE THREAD

**Issue by horva** [scrapinghub/dateparser#22]
Currently it returns something like datetime.datetime(2014, 12, 9, 15, 17, 21, 562654) - date is correct here but time corresponds to import time because of last line in freshness_date_parser.py - we should consider changing this maybe by reinitializing freshness parser each time.

**Comment by Allactaga** [comment]
Resolved in https://github.com/scrapinghub/dateparser/pull/26
