### ISSUE TITLE
question: limit date parsing to only the formats specified in date_formats

### ISSUE THREAD

**Issue by sharky93** [scrapinghub/dateparser#226]
at the moment `dateparser` tries to parse using the date formats specified and if nothing matches falls back to how it would usually parse the given date string?

is there a way to limit it to just the `date_formats` specified?

**Comment by waqasshabbir** [comment]
Hi @sharky93 currently there is no way to restrict the `dateparser` to limit only to given `date_formats`.

If your use case is limited to checking for only certain date_formats, you might be better off using some custom function around `datetime.strptime`.

```
def parse_date(date_string, date_formats):
    for format in date_formats:
        date = datetime.strptime(date_string, format)
        if date:
            return date
```
