### ISSUE TITLE
Please make a new pypi release

### ISSUE THREAD

**Issue by hakanw** [scrapinghub/dateparser#229]
Thanks for your recent fixes! Please release a new version with the fixes. Thanks!

**Comment by waqasshabbir** [comment]
Hi @hakanw it's around the corner, need to tackle #211 and #214 before we release 0.4.1.

**Comment by hakanw** [comment]
Ok!

2016-09-06 11:13 GMT+02:00 Waqas Shabir <notifications@github.com>:
