### ISSUE TITLE
Result of dateparser.parse() should not depend on locale

### ISSUE THREAD

**Issue by alexis-via** [scrapinghub/dateparser#238]
```
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dateparser
>>> dateparser.__version__
'0.5.0'
>>> import locale
>>> locale.getlocale()
(None, None)
>>> dateparser.parse('21-FEB-2016', date_formats=['%d-%b-%Y'], languages=['en'])
datetime.datetime(2016, 2, 21, 0, 0)
>>> locale.setlocale(locale.LC_ALL, 'fr_FR.UTF-8')
'fr_FR.UTF-8'
>>> dateparser.parse('21-FEB-2016', date_formats=['%d-%b-%Y'], languages=['en'])
>>>
```

This is a problem for me: I want to be able to get a good result of dateparser.parse when I give languages=['en'] as argument even if my locale is not english. The users of my software (Odoo) may have any locale, but dateparser.parse() used with the "languages" argument should always give the same result !

**Comment by waqasshabbir** [comment]
Thank you for reporting this. It's a major bug. Will push a fix soon and release a new patch after it's fixed.

**Comment by alexis-via** [comment]
@waqasshabbir I've been hit again by this bug. I am not familiar with the invoice2data codebase, but if I can help to fix this bug, I'd be glad to help.

**Comment by waqasshabbir** [comment]
@alexis-via I'm on it will push a fix soon - likely by the end of this week.

**Comment by alexis-via** [comment]
@waqasshabbir Thanks ! I'll test your fix when it's ready !

**Comment by alexis-via** [comment]
@waqasshabbir If you need help to fix this bug or test a patch, don't hesitate to "ring" me.

**Comment by waqasshabbir** [comment]
@alexis we want to avoid calling `setlocale` multiples times as its an
expensive call. Have figured out a work around it will create a PR in few
hours.

We appreciate all forms of help! Please show us your patch.

**Comment by alexis-via** [comment]
I haven't developped a patch myself yet, because I am not familiar with the codebase.

**Comment by waqasshabbir** [comment]
Sure will ring you when PR is ready. Thanks!

**Comment by alexis-via** [comment]
I tested your PR. It  works well, thank you very much @waqasshabbir . I'll deploy it on one of my installation with invoice2data+odoo/edi/account_invoice_import to see how it behaves on real invoice import.

**Comment by alexis-via** [comment]
@waqasshabbir It would be awsome to have a new release of dateparser on pypi so that everyone can easily benefix from this very important bugfix !

**Comment by waqasshabbir** [comment]
@alexis-via done :)

**Comment by alexis-via** [comment]
Great ! Thanks for this new release and "Viva dateparser 0.6.0" :)
