### ISSUE TITLE
Parsing PDT date correct on 0.3.5 but not 0.5

### ISSUE THREAD

**Issue by adamn** [scrapinghub/dateparser#242]
On version 0.3.5 the PDT datetime below is correctly translated to UTC:

``` python
>>> import dateparser
>>> dateparser.parse('Mon, 12 Sep 2016 04:45:00 PDT')
datetime.datetime(2016, 9, 12, 11, 45)
```

This is the result for 0.5.0:

``` python
>>> import dateparser
>>> dateparser.parse('Mon, 12 Sep 2016 04:45:00 PDT')
datetime.datetime(2016, 9, 12, 4, 45)
```

**Comment by waqasshabbir** [comment]
Adam, can you try with passing `TO_TIMEZONE` setting?

We removed implicit conversion to UTC in 0.5.

On Oct 14, 2016 12:09 AM, "Adam Nelson" <notifications@github.com> wrote:
>
> On version 0.3.5 the PDT datetime below is correctly translated to UTC:
>
> >>> import dateparser >>> dateparser.parse('Mon, 12 Sep 2016 04:45:00
PDT') datetime.datetime(2016, 9, 12, 11, 45)
>
> This is the result for 0.5.0:
>
> >>> import dateparser >>> dateparser.parse('Mon, 12 Sep 2016 04:45:00
PDT') datetime.datetime(2016, 9, 12, 4, 45)

**Comment by adamn** [comment]
Here you go:

```python
>>> parsed = dateparser.parse('Mon, 12 Sep 2016 04:45:00 PDT', settings={'TO_TIMEZONE': 'UTC'})
>>> parsed
datetime.datetime(2016, 9, 12, 11, 45)
>>> dateparser
<module 'dateparser' from '/Users/adamn1/.venvs/dateparser3/lib/python3.5/site-packages/dateparser/__init__.py'>
>>> dir(dateparser)
['DateDataParser', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_default_parser', 'apply_settings', 'conf', 'date', 'date_parser', 'freshness_date_parser', 'languages', 'parse', 'timezone_parser', 'timezones', 'utils']
>>> dateparser.__version__
'0.3.5'
>>>

```
```python
(dateparser) 04:17:54 ~/dev: $ python
Python 2.7.12 (default, Oct  3 2016, 15:02:32)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dateparser
>>> dateparser.parse('Mon, 12 Sep 2016 04:45:00 PDT', settings={'TO_TIMEZONE': 'UTC'})
datetime.datetime(2016, 9, 12, 11, 45)
>>> parsed = dateparser.parse('Mon, 12 Sep 2016 04:45:00 PDT', settings={'TO_TIMEZONE': 'UTC'})
>>> parsed.tzinfo
>>> parsed
datetime.datetime(2016, 9, 12, 11, 45)
>>> dateparser.__version__
'0.5.0'
>>>

```

**Comment by ammar-azif** [comment]
Hi @adamn , to get tzinfo in returned datetime object, set 'RETURN_AS_TIMEZONE_AWARE' to True.

```
>>> dateparser.parse('Mon, 12 Sep 2016 04:45:00 PDT', settings={'TO_TIMEZONE': 'UTC', 'RETURN_AS_TIMEZONE_AWARE': True})
datetime.datetime(2016, 9, 12, 11, 45, tzinfo=<StaticTzInfo 'UTC'>)
>>> dateparser.parse('Mon, 12 Sep 2016 04:45:00 PDT', settings={'TO_TIMEZONE': 'PST', 'RETURN_AS_TIMEZONE_AWARE': True})
datetime.datetime(2016, 9, 12, 3, 45, tzinfo=<StaticTzInfo 'PST'>)
>>> dateparser.parse('Mon, 12 Sep 2016 04:45:00 PDT', settings={'TO_TIMEZONE': 'PDT', 'RETURN_AS_TIMEZONE_AWARE': True})
datetime.datetime(2016, 9, 12, 4, 45, tzinfo=<StaticTzInfo 'PDT'>)
```

**Comment by adamn** [comment]
I'm fine if you guys just close the ticket but it's really not what a user would expect from a higher level library like `dateparser`.  Maybe just have the default for `RETURN_AS_TIMEZONE_AWARE` be `true`?

**Comment by adamn** [comment]
I would say:

 * tzaware if `TO_TIMEZONE` is set to any timezone, even if it's a guess
 * tzaware if `RETURN_AS_TIMEZONE_AWARE` is true, even if it's a guess (Defaulting to UTC)
 * `RETURN_AS_TIMEZONE_AWARE` be true by default

The first two would really help.  The last one is ok to not do if you guys are against it.

**Comment by waqasshabbir** [comment]
@adamn closing this now. Do try new changes and let us know what you think. Thanks for your feedback!
