### ISSUE TITLE
Extraneous symbols are incorrectly ignored

### ISSUE THREAD

**Issue by jfrancos** [scrapinghub/dateparser#258]
E.g.
`dateparser.parse(')(*&^%$#@!7)(*&^%$#@!) )(*&^%$#@!4)(*&^%$#@! )(*&^%$#@!1776)(*&^%$#@!) ')`
returns
`1776-07-04 00:00:00` instead of `None` - I take this to be undesirable behavior.

Whereas with extraneous letters e.g.
`dateparser.parse('q7 4q q1776')`
`None` is returned - which I take to be desirable behavior.

OS: macOS 10.12.1

**Comment by waqasshabbir** [comment]
@jfrancos first string contains characters which the parser treats same as it does comma, period or dash or other popular date delimiters. Hence, you get the date. 

there's a way to parse the second example:

```
dateparser.parse('q7 4q q1776', settings={'SKIP_TOKENS': ['q']})
Out[2]: datetime.datetime(1776, 7, 4, 0, 0)
```
