### ISSUE TITLE
dateparser should pin all requirements versions

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/dateparser#261]
[requiremenst.txt](https://github.com/scrapinghub/dateparser/blob/master/requirements.txt) file has dependencies names without versions specified. This is not good, if some dependency will do breaking update at some point dateparser will break. All packages should probably be pinned to minimal versions that work ok. 

http://nvie.com/posts/pin-your-packages/

I'm talking about this because today I woke up and saw following warnings in logs in production:

```
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  cls._yaml_data = load_yaml(data).pop('settings', {})
/home/pawel/.virtualenvs/scrapy/local/lib/python2.7/site-packages/dateparser/languages/loader.py:46: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

```

what happened is that dateparser relies on ruamel.yaml, yaml updated package and added this deprecation warning, I see this is (probably) fixed in dateparser, but not released yet. It's just a warning so no big deal, BUT it is just as likely that at some point yaml will do breaking update, and I'll get broken project because of dateparser not specyfing version numbers.

**Comment by FichteFoll** [comment]
This seems like a good opportunity to also address the deprecation warning that `ruamel.yaml` emits: Not using a patched safe loader.

Ideally, the safe loader would be subclassed and handling of the `!include` tag be added to that class. Then this loader class should be used for loading.

**Comment by eliasdorneles** [comment]
+1 to pin the versions known to work in `requirements.txt`

However, install_reqiures in `setup.py` should be left loose, only excluding versions known to not work.

**Comment by kennethreitz** [comment]
Correct
