### ISSUE TITLE
More flexible parsing of fractional seconds

### ISSUE THREAD

**Issue by wiseman** [scrapinghub/dateparser#269]
Currently, dateparser is somewhat inflexible in its parsing of fractional seconds (milliseconds, microseconds, etc.):

```
>>> print dateparser.parse('1/1/16 9:02:43.100000')
2016-01-01 09:02:43.100000
>>> print dateparser.parse('1/1/16 9:02:43.1')
None
```

`43.1` is essentially equivalent to `43.1000000` so it would be nice if it parsed as well.

**Comment by waqasshabbir** [comment]
Related to #234
