### ISSUE TITLE
Downstream dependencies ephem and windows is broken

### ISSUE THREAD

**Issue by rnwolf** [scrapinghub/dateparser#273]
Hi

After adding a dependency to convertdate which in turn requires ephem I have a problem.
 
https://github.com/brandon-rhodes/pyephem/issues/115

ephem seems not to run on MS-Windows. I will revert back to an older version of dateparser but it seems that you are constraining the number of places the library can run in.

```
Collecting convertdate (from dateparser->jira-metrics-extract[charting])
  Using cached convertdate-2.1.0-py2.py3-none-any.whl
Requirement already satisfied: jdatetime in c:\users\ieuser\anaconda3\envs\demo1\lib\site-packages (from dateparser->jira-metrics-extract[charting])
Requirement already satisfied: tzlocal in c:\users\ieuser\anaconda3\envs\demo1\lib\site-packages (from dateparser->jira-metrics-extract[charting])
Requirement already satisfied: umalqurra in c:\users\ieuser\anaconda3\envs\demo1\lib\site-packages (from dateparser->jira-metrics-extract[charting])
Requirement already satisfied: cycler in c:\users\ieuser\anaconda3\envs\demo1\lib\site-packages (from matplotlib; extra == "charting"->jira-metrics-extract[charting])
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,>=1.5.6 in c:\users\ieuser\anaconda3\envs\demo1\lib\site-packages (from matplotlib; extra == "charting"->jira-metrics-extract[charting])
Requirement already satisfied: oauthlib>=0.6.2 in c:\users\ieuser\anaconda3\envs\demo1\lib\site-packages (from requests-oauthlib>=0.3.3->jira->jira-metrics-extract[charting])
Collecting ephem<3.8,>=3.7.5.3 (from convertdate->dateparser->jira-metrics-extract[charting])
  Using cached ephem-3.7.6.0.tar.gz
Building wheels for collected packages: ephem
  Running setup.py bdist_wheel for ephem: started
  Running setup.py bdist_wheel for ephem: finished with status 'error'
......
error: Microsoft Visual C++ 14.0 is required.
etc
```

**Comment by asadurski** [comment]
@rnwolf, can you install Visual C++ Build Tools (http://landinghub.visualstudio.com/visual-cpp-build-tools) and try again?
I believe this only happens with Python 3.5. By the way, can you confirm your environment setup (just so that we know for the future).

**Comment by waqasshabbir** [comment]
@rnwolf if you don't use calendars and only wants the parsing capabilities, you can install dateparser now without having to install `convertdate`. Please re-open the issue if @asadurski solution doesn't work for you. Thanks!

**Comment by waqasshabbir** [comment]
@rnwolf if you don't use calendars and only wants the parsing capabilities, you can install dateparser now without having to install `convertdate`. Please re-open the issue if the issue persists with the latest release or @asadurski solution doesn't work for you. Thanks!
