### ISSUE TITLE
Disabling relative times

### ISSUE THREAD

**Issue by JohannesBuchner** [scrapinghub/dateparser#312]
Hi all,

I am very happy to use dateparser. It is very successful for me in parsing a lot of date formats.
I have a use case however where relative dates do not make sense. Therefore I would like to disable this functionality, limiting the parsing to absolute times only.

I am happy to contribute a patch, if you are interested and if can point me in the right direction.

Cheers,
                 Johannes

**Comment by JohannesBuchner** [comment]
I found that I can disable the "freshness_parser" with

`dateparser.date._DateLanguageParser._try_freshness_parser = lambda self: False`

Not elegant, but seems to work for now.

**Comment by waqasshabbir** [comment]
Hi @JohannesBuchner patches are always welcome. To continue with your contribution please look at [settings](https://github.com/scrapinghub/dateparser/blob/master/data/settings.yaml). Normally, everything which modifies/control dateparser behavior is implemented as a setting.

**Comment by noviluni** [comment]
In the last version `0.7.4` this can be done through the `PARSERS` setting. :tada:
