### ISSUE TITLE
Requiring a time component

### ISSUE THREAD

**Issue by JohannesBuchner** [scrapinghub/dateparser#313]
Dear all,

I need to check if a time was specified in a given text.
For example, I have
`dateparser.parse("7:22 AM (15APR)")`
or 
```
reference = dateparser.parse("15APR 2010") 
s = dateparser.conf.Settings().replace(RELATIVE_BASE=reference)
dateparser.parse("7:22 AM", settings=s)
```

and get `datetime.datetime(2010, 4, 15, 7, 22)`

But I might also have dates like 
`dateparser.parse("15APR", settings=s)`
which do not set a time.

How can I check or require that the date parser found and set a time?

I could set the hour&minute&seconds to random values, then check if they were modified; but I would have to do this twice to be sure that the time was not set (which is 2x slower).

get_date_data returns period='day' for both cases.

Thanks,
               Johannes

**Comment by cricketts** [comment]
I could also use this feature. It seems that if a period of `hour` and `minute` was supported that could work, or a flag similar to `STRICT_PARSING` which raises an error when an hour or minute isn't parsed.

For what it's worth, this was our workaround as a best-effort approach to detect when hours/minutes were not parsed:

```
parsed_date = dateparser.parse(date_text)
if parsed_date.hour == 0 and parsed_date.minute == 0 and \
        '00:00' not in date_text and \
        '12:00' not in date_text:
    # raise an error
```

**Comment by gypapp** [comment]
It looks like a [deliberate choice](https://github.com/scrapinghub/dateparser/blob/master/dateparser/parser.py#L278-L281) not to return `time` as period but `day` instead (if I am not mistaken):
```
    def _get_period(self):
        for period in ['time', 'day']:
            if getattr(self, period, None):
                return 'day'
```
So the fix should be easy but I could not tell what the original purpose was.
@waqasshabbir could you tell us why 'time' period support is omitted by `DateDataParser`

**Comment by asadurski** [comment]
Well, `period` was supposed to be the level of granularity of recognised date. So it was never meant to get down to time level.
But as you said, that's also the clearest signal of parsing the time...
To keep backwards compatibility, I suggest adding a setting switch that would influence returned period.
Does `RETURN_TIME_AS_PERIOD` sound right?
What we can also think about is whether just `time` is enough, or we should specify whether it's hour, minute, up to microsecond.

**Comment by asadurski** [comment]
PR built according to previous comment: https://github.com/scrapinghub/dateparser/pull/545.

**Comment by gypapp** [comment]
Sorry @asadurski for the long delay I was away a bit.
`RETURN_TIME_AS_PERIOD` sounds good to me as well. I was also thinking of what you asked about making such an option more granular for hours, minutes and so on. I would say for the time being this PR as it now suffices our current needs because the main issue was to tell whether the time part was actually parsed or just a default was used.

May I ask when it can be expected to be released?
