### ISSUE TITLE
Relative dates in FreshnessDateDataParser

### ISSUE THREAD

**Issue by fedealvarez** [scrapinghub/dateparser#325]
If I want to parse relative dates that don't include the word `in` it will always return a date in the past, which it's not ideal and it should take into account the `PREFER_DATES_FROM` setting.
Example:
```
In [2]: datetime.now()
Out[2]: datetime.datetime(2017, 6, 14, 18, 1, 4, 654628)
In [5]: dateparser.parse('1 month', settings={'PREFER_DATES_FROM': 'future'})
Out[5]: datetime.datetime(2017, 5, 14, 18, 1, 26, 815558)
```

**Comment by dipanm** [comment]
As such string "1 month" is a period not a date. It should return a relative delta which if added (or subtracted) from now should give the desired date. Look at #344 and do give your feedback.

**Comment by noviluni** [comment]
This was fixed in: https://github.com/scrapinghub/dateparser/pull/530
