### ISSUE TITLE
Extract dates in document

### ISSUE THREAD

**Issue by dvaldivia** [scrapinghub/dateparser#326]
Hi, I'm trying to figure out how to identify all the dates in a paragraph, dateparser seems like it would crush the dates after they've been identified but I wonder if someone can think of a better approach other than building a set of regex to extract every possible date format

example paragraph:

"The client arrived to the office for the first time in March 3rd, 2004 and got serviced, after a couple of months, on May 6th 2004, the customer returned indicating a defect on the part"

as you can see there's two dates, there could be more, in the text and I'd like to extract all of them if possible, but right now all I can think of is writing a large number of regex.

Thanks for the advise.

**Comment by waqasshabbir** [comment]
Hi @dvaldivia we are working on this feature as part of GSOC this summer and will have it ready by the summer end. Once the PR is ready to be reviewed, I'll ping you so you can test it. Thanks!

**Comment by damianoporta** [comment]
Hello! news?

**Comment by asadurski** [comment]
Well, you're welcome to try out and give feedback to the feature from https://github.com/scrapinghub/dateparser/pull/324. That goes more or less like this:

```python
In [1]: from dateparser.search import search_dates
In [2]: search_dates("The client arrived to the office for the first time in March 3rd, 2004 and got serviced, after a couple of months, on May 6th 2004, the customer returned indicating a defect on the part")
Out[2]: 
[(u'in March 3rd, 2004 and', datetime.datetime(2004, 3, 3, 0, 0)),
 (u'on May 6th 2004', datetime.datetime(2004, 5, 6, 0, 0))]
```

**Comment by damianoporta** [comment]
Thank you! But, when it will be merged @asadurski ?

**Comment by asadurski** [comment]
Feature added in version 0.7.0.
Closing.

**Comment by alvaroabascar** [comment]
@asadurski , any plans on allow `date_formats` for `search_dates`?
