### ISSUE TITLE
Inconsistent behavior when hour=0 and am/pm is present

### ISSUE THREAD

**Issue by filwaitman** [scrapinghub/dateparser#329]
Hi there!

First, thanks for this awesome project!  =D

I'm seeing an inconsistent result with `dateparser==0.6.0`/`python==3.5.2` when date_string passed in is at midnight/noon and meridian info is present. See below:

```python
>>> import dateparser

>>> dateparser.parse('2016-12-31 01:10') is None
False

>>> dateparser.parse('2016-12-31 01:10am') is None
False

>>> dateparser.parse('2016-12-31 00:10') is None
False

>>> dateparser.parse('2016-12-31 00:10am') is None
True
```

Is it an issue? Am I missing something?

Thanks!

**Comment by wRAR** [comment]
Hello @filwaitman , I don't think hour can be zero when am/pm is present? [Wikipedia](https://en.wikipedia.org/wiki/12-hour_clock) agrees with me.

**Comment by filwaitman** [comment]
wow, this is old.  =P

ok @wRAR, it makes sense then. Thanks!
