### ISSUE TITLE
dateparser.parse('to') = datetime.datetime(2017, 7, 6, 0, 0)

### ISSUE THREAD

**Issue by kartikye** [scrapinghub/dateparser#330]

**Comment by kartikye** [comment]
>>> dateparser.parse('a')
datetime.datetime(2017, 1, 11, 0, 0)

**Comment by sarthak5** [comment]
that's because 'to' translates to thursday in Finnish, and 'a' is simplified as 1 and since incomplete dates are parsed in dateparser the above results are generated.

**Comment by jraede** [comment]
Why does "a" get simplified to "1"? Are there countries where that is used? If so, shouldn't that result be limited to just those languages/locales?

**Comment by Gallaecio** [comment]
Limiting the language to English fixes the case of `to`, but this looks wrong indeed:
```

>>> dateparser.parse('a', languages=['en'])
datetime.datetime(2019, 1, 11, 0, 0)
```

**Comment by noviluni** [comment]
From the README (https://github.com/scrapinghub/dateparser#false-positives):

> False positives
> 
> dateparser will do its best to return a date, dealing with multiple formats and different locales. For that reason it is important that the input is a valid date, otherwise it could return false positives.
> 
> To reduce the possibility of receiving false positives, make sure that:
> 
> * The input string it's a valid date and it doesn't contain any other words or numbers.
> * If you know the language or languages beforehand you add them through the languages or locales properties.
> 
> On the other hand, if you want to exclude any of the default parsers (timestamp, relative-time...) or change the order in which they are executed, you can do so through the settings PARSERS.


Since we added this in the README this can't be considered a bug anymore. As @sarthakmadaan mentioned "to" it's an abbreviation for "Thursday" in Finnish, so the result is technically correct.

Thank you guys for the feedback :)
