### ISSUE TITLE
Error parsing abbreviated tuesday in Italian

### ISSUE THREAD

**Issue by akiross** [scrapinghub/dateparser#337]
I was trying to parse dates in italian in the format `%a %d %b %Y`, but found a bug with abbreviation of tuesday (Martedì -> Mar). This issue is similar with the one you have/had in French (Issue #268, maybe solved in #283).

    import dateparser as dp
    for a, b in enumerate('Lun Mar Mer Gio Ven Sab Dom'.split(), 23):
        print(dp.parse('{} {} Gen 2017'.format(a, b)))

Produces
```
2017-01-23 00:00:00
None
2017-01-25 00:00:00
2017-01-26 00:00:00
2017-01-27 00:00:00
2017-01-28 00:00:00
2017-01-29 00:00:00
```

Indeed, abbreviation "Mar" for "Martedì" is missing in `it.yaml`.

I don't know if this an issue or not, but there's a clash in abbreviating Martedì (Tuesday) and Marzo (March) in Italian, as both are abbreviated "Mar".

**Comment by noviluni** [comment]
To avoid duplicated issues I will close this issue in favor of https://github.com/scrapinghub/dateparser/issues/676 (as it's more generic)

Thanks
