### ISSUE TITLE
ruamel.yaml version pinned in GitHub release but not on PyPI

### ISSUE THREAD

**Issue by porglezomp** [scrapinghub/dateparser#342]
The release of version 0.6 published on PyPI doesn't contain the `<0.14` in `setup.py` that's claimed in the release notes. (This is causing one of our automated builds to fail.)

**Comment by westshawn** [comment]
The work-around for us was to run 
`pip install ruamel.yaml==0.13.14`
prior to 
`pip install dateparser==0.6.0`

otherwise, dateparser tried and failed to install the latest ruamel (0.15.28)

**Comment by porglezomp** [comment]
It seems like that workaround didn't actually resolve it—it was still installing both versions—we just got lucky because ruamel.yaml updated again (0.15.29) and fixed wheels on Windows.

**Comment by westshawn** [comment]
Good catch @porglezomp! 
Timing is everything.

**Comment by asadurski** [comment]
I just wanted to clarify - the problem with installation happens on Windows, if the Windows wheels for the latest ruamel.yaml release are not yet present.
Is that correct?

**Comment by westshawn** [comment]
Correct.

**Comment by asadurski** [comment]
ruamel.yaml removed from dependencies.
Thank you for reporting!
