### ISSUE TITLE
Error with relative dates in french like "il y a 3 années"

### ISSUE THREAD

**Issue by olivierreberga** [scrapinghub/dateparser#354]
The following is working:
- il y a 1 semaine
- il y a 1 semaines
- il y a 2 semaine
- il y a 2 semaines

Same with "jour" / "jours"
Same with "mois"

But issues with "an" and "années"
- il y a 1 an >>> OK
- il y a 1 ans >>> KO
- il y a 2 an >>> OK
- il y a 2 ans >>> KO
- il y a 1 année >>> OK
- il y a 1 années >>> KO
- il y a 2 année >>> OK
- il y a 2 années >>> KO

**Comment by starrify** [comment]
I'm not sure which version of this package you're using, but according to [the related code](https://github.com/scrapinghub/dateparser/blob/master/data/languagefiles/fr.yaml#L73), it shall work properly with "an" / "année" / "années", but not "ans".

:point_up: Testing on my local machine also supports that.

**Comment by olivierreberga** [comment]
I'm using dateparser v.0.6.0 on python 2.7 on windows,
Here below some code:

import dateparser
dateparser.parse('il y a 1 semaine')
Out[50]: datetime.datetime(2017, 10, 23, 15, 10, 4, 21000)
dateparser.parse('il y a 1 an')
Out[51]: datetime.datetime(2016, 10, 30, 15, 10, 30, 490000)
dateparser.parse('il y a 1 ans')
dateparser.parse('il y a 2 an')
Out[53]: datetime.datetime(2015, 10, 30, 15, 10, 52, 949000)
dateparser.parse('il y a 2 ans')
