### ISSUE TITLE
Language - Swedish: Abbreviation not correct

### ISSUE THREAD

**Issue by thernstig** [scrapinghub/dateparser#368]
The Swedish language file and abbreviation currently uses `sv` as the abbreviation. According to ISO 3166-1, which I assume is what dateparser wants to follow, it should be `se`

see https://en.wikipedia.org/wiki/ISO_3166-1

**Comment by thernstig** [comment]
@eragnms

**Comment by Styrke** [comment]
I think the current name of the Swedish language file is correct.

[ISO 3166-1 according to Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1) "defines codes for the names of _countries_, dependent territories, and special areas of geographical interest," not languages.

[ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) on the other hand defines two-letter language codes and has Swedish represented by `sv`.

**Comment by thernstig** [comment]
@Styrke Agreed - good catch. Closing this.
