### ISSUE TITLE
Custom date delimiters

### ISSUE THREAD

**Issue by damianoporta** [scrapinghub/dateparser#378]
Hello,
is it possible to use custom date's delimiters?
For example, in my case, there are dates with this format: dd.mm.YYYY
Can i add the dot delimiter somehow?

**Comment by Gallaecio** [comment]
I think the answer is the `date_formats` parameter of `dateparser.parse()`.

**Comment by noviluni** [comment]
Yes, you can use the `date_formats` parameter. If your problem is because the day/month distinction, you can also use the `DATE_ORDER` setting. 

Closed as solved.

Feel free to reopen this issue if you have any other question/problem.
