### ISSUE TITLE
Unable to parse 'one week ago'

### ISSUE THREAD

**Issue by browniebroke** [scrapinghub/dateparser#383]
After updating to the latest release, we are unable to parse 'one week ago', although '1 week ago' works. It seems to be a regression from 0.6.0 as downgrading fixes the problem. I'm running Python 3.6.3, under macOS.

```python
>>> import dateparser
>>> dateparser.__version__
'0.7.0'
>>> dateparser.parse('one week ago')
>>> dateparser.parse('1 week ago')
datetime.datetime(2018, 2, 1, 18, 47, 8, 496179)
>>>
```

```python
>>> import dateparser
>>> dateparser.__version__
'0.6.0'
>>> dateparser.parse('one week ago')
datetime.datetime(2018, 2, 1, 18, 43, 28, 833883)
>>>
```

**Comment by asadurski** [comment]
Indeed, looks like we have a regression on recognizing of numerals. And we only have 'a week ago' and '1 week ago' in the tests, so this was missed.
Thank you for reporting this.

**Comment by josericardo** [comment]
Hey, just stumbled on this too. I also noticed that in the 0.6.0 version the support was kinda limited:

```
In [10]: [dateparser.parse('{} days ago at 00:00'.format(d)) for d in ('one', 'two', 'three', 'four', 'five')]
Out[10]: 
[datetime.datetime(2018, 5, 1, 0, 0),
 datetime.datetime(2018, 4, 30, 0, 0),
 None,
 None,
 None]
```

**Comment by omer5985** [comment]
Hey are you planning to fix this bug for the next version?

**Comment by eLRuLL** [comment]
@omer5985 there is a WIP in #477 but we are still not sure of the approach to take.

**Comment by noviluni** [comment]
Hi, thank you all for pointing this up. This issue was fixed (https://github.com/scrapinghub/dateparser/pull/593), and you can use now the last dateparser version (0.7.4).

Thank you for all your comments! :star2:
