### ISSUE TITLE
ummalqurra is supported on Python 3

### ISSUE THREAD

**Issue by dotlambda** [scrapinghub/dateparser#385]
Since umalqurra is supported on Python 3 (cf. https://github.com/tytkal/python-hijiri-ummalqura/pull/5), the tests in https://github.com/scrapinghub/dateparser/blob/1764bcfb4932b8928541d8ff58c91b391c15e1e5/tests/test_hijri.py#L9 should be enabled.

**Comment by wRAR** [comment]
Unfortunately, the latest release on pypi is still 0.2 which is older than that change.
