### ISSUE TITLE
history.html on readdocs does not properly format bullet points

### ISSUE THREAD

**Issue by thernstig** [scrapinghub/dateparser#389]
See: https://dateparser.readthedocs.io/en/latest/history.html

Bullet-points used on the page show up as an asterisk instead of a bullet. This is only true for part of the bullet lists.

**Comment by asadurski** [comment]
Good point, thank you.
The formatting was fixed in https://github.com/scrapinghub/dateparser/pull/384, but ReadTheDocs still displayed the version from the release commit. Rebuilt.

**Comment by thernstig** [comment]
@asadurski Looks much better! Good job.
