### ISSUE TITLE
Problem in Danish

### ISSUE THREAD

**Issue by leentheone** [scrapinghub/dateparser#390]
Hi man. Can you add handling of this phrase in Danish: "Mindre end 1 minut siden". On English: "Less then 1 minutes ago".
Thx!

**Comment by elgehelge** [comment]
This is already in there:
https://github.com/scrapinghub/dateparser/blob/eb9614aca39ad9b4cc11ac84fb405af0f4a36b06/dateparser/data/date_translation_data/da.py#L294
