### ISSUE TITLE
search_dates not finding date with trailing comma

### ISSUE THREAD

**Issue by githubmlai** [scrapinghub/dateparser#391]
Hi, 

"search_dates" is not working for the below use case.
-------------------
from dateparser.search import search_dates

has_comma = "9/3/2017 , "
no_comma = "9/3/2017 "

print(search_dates(has_comma, languages=['en']))
print(search_dates(no_comma, languages=['en']))

-----------------
Console output:

/home/ubuntu/.virtualenvs/dsh_v2/bin/python /home/ubuntu/.PyCharmCE2017.1/config/scratches/scratch_2.py
None
[('9/3/2017', datetime.datetime(2017, 9, 3, 0, 0))]

Process finished with exit code 0

---------------
I am using  "dateparser==0.7.0" and Python 3.5.2

**Comment by asadurski** [comment]
Bug confirmed (found similar effect with apostrophe — `9/3/2017 '`). Thank you for reporting this.
