### ISSUE TITLE
Properly parsing 'Wednesday'

### ISSUE THREAD

**Issue by TYMichaelChen** [scrapinghub/dateparser#392]
Hi,

I've been using this great library for a while but I'm running into an issue with parsing relative dates like "wednesday". This returns the past week's wednesday (if today is Sunday (3/4/18), it'll return (2/28/18). I know there's a setting for `PREFER_DATES_FROM: future` but the problem with that is if I have that turned on, wednesday parses correctly to 03/07/18. However,  if we then try to parse 03/07/18 it'll become 03-07-2**1**18 ( notice it becomes 2118 rather than 2018 due to the [line](https://github.com/scrapinghub/dateparser/blob/master/dateparser/parser.py#L400) here). What's the best solution to account for parsing both wednesday & 03/07/18 correctly?

I guess the real bug is with `PREFER_DATES_FROM: future` parsing 09/07/18 as 09-07-2118. That doesn't seem like the right behavior to just add 100 years if the future flag is set since the closest future date is 09-07-2018 not 09-07-2118

**Comment by asadurski** [comment]
Hello!
Thank you for voicing that problem, but at the moment I can't reproduce it:
```
In:  dateparser.parse("09/07/18", settings={"PREFER_DATES_FROM": "future"})
Out: datetime.datetime(2018, 9, 7, 0, 0)

In:  dateparser.parse("02/07/18", settings={"PREFER_DATES_FROM": "future"})
Out: datetime.datetime(2118, 2, 7, 0, 0)
```
So, it looks like the behaviour is correct. If the date is in the past, we skip to the nearest future date that fits. If it's in the future, we leave it like that.
If your results differ, could you post more details about your system configuration?

**Comment by trideeprath** [comment]
@asadurski The issue here is in finding the nearest future. 
The nearest future is "year +1" and not "year +100" 

https://github.com/scrapinghub/dateparser/issues/468

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback from the original author after indicating that we cannot reproduce the issue. @trideeprath’s feedback can be handled at #468 instead.
