### ISSUE TITLE
'me' = March 14, 2018? 'are' = March 11, 2018?

### ISSUE THREAD

**Issue by nbgraham** [scrapinghub/dateparser#394]
```python
from dateparser.search import search_dates
search_dates('You can reach me on the phone')
[('me', datetime.datetime(2018, 3, 14, 0, 0))]
search_dates('None of these are dates')
[('are', datetime.datetime(2018, 3, 11, 0, 0))]
```

**Comment by starrify** [comment]
Because it is not the case that everyone speaks only English.

It might have been helpful if you ever tried:
```
search_dates('You can reach me on the phone', ['en'])
search_dates('None of these are dates', ['en'])
```

You may also want to try this:
```
search_dates('You can reach me on the phone', ['fr'])
```

Well, personally I do think it's a good idea to include also the corresponding languages in the return value of `search_dates`.

**Comment by nbgraham** [comment]
Ok, sorry. I didn't find a function signature for search_dates in the [docs](https://dateparser.readthedocs.io/en/latest/)

Thanks!

**Comment by starrify** [comment]
There's definitely nothing to apologize for. And this ticket is fairly helpful, as it reveals that:
1. Return value of `search_dates` may be further enhanced.
2. The docs may be improved.

Much appreciated! :)

**Comment by asadurski** [comment]
And just to explain the case with `are`, that's the abbreviation for "Sunday" in Samburu.

Issues created, @starrify. That's exactly what we'll do :muscle:
