### ISSUE TITLE
Necessary documentation improvements

### ISSUE THREAD

**Issue by asadurski** [scrapinghub/dateparser#397]
- extensive entry for `search_dates()`
- extend list of supported languages and locales

TBC

**Comment by rennerocha** [comment]
I believe that removing references to Scrapy Cloud is interesting too (https://dateparser.readthedocs.io/en/latest/installation.html#deploying-dateparser-in-a-scrapy-cloud-project), as the library is general enough and not directly related to Scrapy.

**Comment by Gallaecio** [comment]
>     * extensive entry for `search_dates()`

Could you elaborate? What do we need to cover beyond what is already covered in https://dateparser.readthedocs.io/en/latest/#search-for-dates-in-longer-chunks-of-text?

**Comment by lucasdutraf** [comment]
> I believe that removing references to Scrapy Cloud is interesting too (https://dateparser.readthedocs.io/en/latest/installation.html#deploying-dateparser-in-a-scrapy-cloud-project), as the library is general enough and not directly related to Scrapy.

Is this change still needed, @rennerocha ? I could work on it

**Comment by noviluni** [comment]
I have just created a ticket to improve the `search_dates` section in the docs: https://github.com/scrapinghub/dateparser/issues/737

As we currently have a list of locales (it is in the README, I think we should move it to the docs, but that's another point) and we have an open ticket regarding the section about Scrapy Cloud in the docs: https://github.com/scrapinghub/dateparser/issues/724, I think we can close this ticket, as it's too broad and incomplete.

Thank you, guys!
