### ISSUE TITLE
Can't parse data from string '2018-03-21T00:36:04-00:00'

### ISSUE THREAD

**Issue by podolskyi** [scrapinghub/dateparser#402]
Name: dateparser
Version: 0.6.0

`
In [1]: import dateparser

In [2]: dateparser.parse('2018-03-21T00:36:04-00:00')

In [3]:
`
if strip '-00:00' works.

**Comment by noviluni** [comment]
Hi @podolskyi this has been fixed in the last version `0.7.4` :tada:
