### ISSUE TITLE
Increasingly high CPU utilization in 0.7.0

### ISSUE THREAD

**Issue by DougHaber** [scrapinghub/dateparser#404]
## Overview

After upgrading `dateparser` from `0.6.0` to `0.7.0` a program that normally had very low CPU usage began taking up an entire CPU.    Any time it was restarted, the CPU usage would trend upwards until it was around 100%. 

The was encountered with Python 2 (`2.7.9` and `2.7.14`) and has been seen on Debian, CentOS, and MacOS.   In each case, pinning the version to `0.6.0` resolves the issue.

 ## Test Case

The following code can be used to cause the issue:

```python
#!/usr/bin/env python                                                                                                  

import dateparser
import time

cycle = 1

while True:
    start_time = time.time()

    for i in range(0, 50):
        dateparser.parse('Sun Apr  1 01:00:53 EDT 2018')
        dateparser.parse('invalid')

    elapsed_time = time.time() - start_time

    print("Round %d: %.2f seconds" % (cycle, elapsed_time))

    cycle += 1
    time.sleep(1)
```

This encounters the high CPU utilization only when we attempt to parse both valid and invalid dates.   

### 0.6.0

When run with version `0.6.0`, the amount of time needed to parse the dates each cycle remains flat:

```
Round 1: 13.24 seconds
Round 2: 15.53 seconds
Round 3: 13.46 seconds
Round 4: 13.32 seconds
Round 5: 13.43 seconds
Round 6: 13.22 seconds
Round 7: 12.92 seconds
Round 8: 12.97 seconds
Round 9: 13.02 seconds
Round 10: 12.96 seconds
```

### 0.7.0

When run with version `0.7.0`, the amount of time needed to parse the dates steadily increases with each cycle:

```
Round 1: 15.45 seconds
Round 2: 10.03 seconds
Round 3: 10.77 seconds
Round 4: 14.29 seconds
Round 5: 13.96 seconds
Round 6: 14.35 seconds
Round 7: 15.08 seconds
Round 8: 17.05 seconds
Round 9: 19.81 seconds
Round 10: 20.54 seconds
```

**Comment by DougHaber** [comment]
Testing again with Python3 using the latest  version (`0.7.1`):

```
Round 1: 3.11 seconds
Round 2: 1.64 seconds
Round 3: 1.80 seconds
Round 4: 3.03 seconds
Round 5: 3.20 seconds
Round 6: 2.80 seconds
Round 7: 3.46 seconds
Round 8: 3.02 seconds
Round 9: 3.34 seconds
Round 10: 4.83 seconds
Round 11: 6.03 seconds
Round 12: 4.77 seconds
Round 13: 4.84 seconds
Round 14: 4.71 seconds
Round 15: 4.49 seconds
Round 16: 4.73 seconds
Round 17: 4.92 seconds
Round 18: 5.20 seconds
Round 19: 5.79 seconds
Round 20: 5.76 seconds
Round 21: 6.40 seconds
Round 22: 6.92 seconds
Round 23: 6.70 seconds
Round 24: 7.79 seconds
Round 25: 7.72 seconds
```
Performance is better in Python3, but we get the same trend where the time to complete keeps increasing.

**Comment by noviluni** [comment]
Hi @DougHaber this should be fixed (or at least totally mitigated) in the last release `0.7.4`.

**Comment by DougHaber** [comment]
Looks great!  Retested, and after 100 cycles, times stay flat.  It is also much faster now.  Thanks for fixing that.
