### ISSUE TITLE
return detected format

### ISSUE THREAD

**Issue by seyed1991** [scrapinghub/dateparser#409]
Hi
If it's possible please add a function to return detected format as well. Something like this:
func('17/12/15')
<datetime.datetime(2017, 12, 15, 0, 0) 'YY/m/d'>

**Comment by Gallaecio** [comment]
Related StackOverflow question: https://stackoverflow.com/q/57742320/939364

**Comment by noviluni** [comment]
Closed as duplicate of this: https://github.com/scrapinghub/dateparser/issues/341
