### ISSUE TITLE
Dates before "01/01/69" get parsed to 20** instead of 19**

### ISSUE THREAD

**Issue by amondal2** [scrapinghub/dateparser#420]
Not a bug per se, but I wanted to have a discussion around parsing dates where the millennium is not specified. It looks like any date of the format "DD/MM/YY" before "01/01/69" gets parsed to the next millennium. Is this intended behavior? Is there a reason that date specifically gets parsed to 1969 but anything before gets parsed to 20** ? this is python3.4, dateparser 0.7.0. thanks all! 

```
>>> value = "01/01/69"
>>> dateparser.parse(value)
datetime.datetime(1969, 1, 1, 0, 0)
>>> value = "12/31/68"
>>> dateparser.parse(value)
datetime.datetime(2068, 12, 31, 0, 0)
```

**Comment by stuartspotlight** [comment]
You could try setting it to prefer setting the time in the past, so:-
```
a = dateparser.parse("12/31/68")
```
Would become:-
```
a = dateparser.parse("12/31/68", settings={'PREFER_DATES_FROM': 'past'})
```
which would produce the date you're expecting. I guess they just had to set a cut off for when to expect the 19xx's and when to expect the 20xx's and decided on the first of January 1969, 1 year before the start of unix time.
