### ISSUE TITLE
Error at Import

### ISSUE THREAD

**Issue by anbire** [scrapinghub/dateparser#423]
Hi,

I have met the following issue at importation (after installing with pip on windows). It was ok before the last conda update.
Thanks a lot,
A.

In [1]: import dateparser
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b16dd8b80396> in <module>()
----> 1 import dateparser

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\dateparser\__init__.py in <module>(
      2 __version__ = '0.7.0'
      3
----> 4 from .date import DateDataParser
      5 from .conf import apply_settings
      6

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\dateparser\date.py in <module>()
      8
      9 import six
---> 10 import regex as re
     11 from dateutil.relativedelta import relativedelta
     12

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\regex.py in <module>()
    398 # Internals.
    399
--> 400 import _regex_core
    401 import _regex
    402 from threading import RLock as _RLock

~\AppData\Local\Continuum\Anaconda3\lib\site-packages\_regex_core.py in <module>()
     19 from collections import defaultdict
     20
---> 21 import _regex
     22
     23 __all__ = ["A", "ASCII", "B", "BESTMATCH", "D", "DEBUG", "E", "ENHANCEMATCH",

ImportError: DLL load failed: Le module spécifié est introuvable.

**Comment by AshwiniPatil5** [comment]
facing the same issue.. any update on this? how did you resolve this one?

**Comment by wRAR** [comment]
@anbire @AshwiniPatil5 this error most likely means the `regex` module was not installed properly, you should try reinstalling it and if there is an error fixing it. This doesn't look like a problem with dateparser.

**Comment by Gallaecio** [comment]
May we close this in favor of #505?

**Comment by Gallaecio** [comment]
This issue is not actually related to #505, but I guess we can close given the lack of further feedback from the reporter and our inability to reproduce the issue.
