### ISSUE TITLE
Inconsistency in the parser behaviour with and without date_formats, with respect to choosing day of month.

### ISSUE THREAD

**Issue by alvaroabascar** [scrapinghub/dateparser#435]
- version: 0.7.0

This is the expected default behaviour of `dateparser.parser`. If we do not specify the day in the date, we get the same day of the month as today (I'm writting as of July 19th 2018).

```python3
dateparser.parse('august 2016')
# >> datetime.datetime(2016, 8, 19, 0, 0)
```
Now let's say we want to parse "august-16" as "august of 2016", so we use the custom format `"%B-%y"`. We obtain the following result:
```python3
dateparser.parse('august-16', date_formats=['%B-%y'])
# >> datetime.datetime(2016, 8, 31, 0, 0)
```

In this case, instead of obtaining the same result as before, we got the last day of august (31). Unless I'm missing something, I believe the result should be the same in both cases.

I have seen that the behaviour comes from [here](https://github.com/scrapinghub/dateparser/blob/master/dateparser/date.py#L140) in function `parse_with_formats`. I don't know what it means that  "the first [day] is usually out of range" in the comment *"If format does not include the day, use last day of the month instead of first, because the first is usually out of range."*

![screenshot from 2018-07-19 11-39-19](https://user-images.githubusercontent.com/7307772/42934864-880ccd94-8b48-11e8-99e1-894c8edfa627.png)

**Comment by noviluni** [comment]
This was fixed in https://github.com/scrapinghub/dateparser/pull/611

So, closing this! :)
