### ISSUE TITLE
Missing abbreviation of Russian Thursday

### ISSUE THREAD

**Issue by acheleo** [scrapinghub/dateparser#436]
Parsing the following string 
`'19/07/18 Чтв 21:14:09'`
Will result in None.
If you look at [the code](https://github.com/scrapinghub/dateparser/blob/master/dateparser/data/date_translation_data/ru.py)
You'll see that the entry for Thursday contains 
```
        "четверг",
        "чт"
```
I.e missing чтв.

**Comment by wRAR** [comment]
@acheleo actually there is no 3-letter abbreviations for weekdays there.

**Comment by Gallaecio** [comment]
Solved by https://github.com/scrapinghub/dateparser/pull/1082
