### ISSUE TITLE
dateparser.search.search_dates() hangup

### ISSUE THREAD

**Issue by pulsar70** [scrapinghub/dateparser#439]
Example : when I apply it on the following webpage content 
http://www.rulers.org/frgovt2.html
the function still does not return after 20 minutes runtime on a Core i7-7700K with 32GB RAM.

I know this content has lots of dates, but is there some infinite loop or critical recursion problem behind this unending processing time ?...

**Comment by AmitMY** [comment]
Try: `languages=['en']`, for me, it is 50 times faster.

**Comment by noviluni** [comment]
Hi @pulsar70 

The last `dateparser` version (0.7.4) implemented some performance fixes and this seems to work correctly. I tried to parse the content of that website and it needed less than 10 seconds to do it.

I will close this issue but feel free to open it again if your problem persists. :slightly_smiling_face:
