### ISSUE TITLE
Skipped tests should be converted

### ISSUE THREAD

**Issue by Allactaga** [scrapinghub/dateparser#44]
During the migration to the declarative languages approach we marked some tests as skipped, because the nature of code in those places almost completely changed. Now, when the behavior of working with languages is more likely finalized, those skipped tests should be rewritten to test that new code is still working for input from old cases. Tests should be designed in a way described [here](https://github.com/scrapinghub/dateparser/issues/31#issuecomment-71035831).

**Comment by tsrdatatech** [comment]
I will assign this to myself since I am already doing issue #31

**Comment by waqasshabbir** [comment]
Fixed by #85
