### ISSUE TITLE
Test fails as it requires an specific locale installed

### ISSUE THREAD

**Issue by rennerocha** [scrapinghub/dateparser#448]
Tests are failing in these lines if I don't have 'fr_FR.UTF-8' locale installed in my computer:

https://github.com/scrapinghub/dateparser/blob/master/tests/test_utils_strptime.py#L45
https://github.com/scrapinghub/dateparser/blob/master/tests/test_utils_strptime.py#L57
https://github.com/scrapinghub/dateparser/blob/master/tests/test_utils_strptime.py#L62

```
======================================================================
ERROR: test_parsing_date_should_fail_using_datetime_strptime_if_locale_is_non_english (tests.test_utils_strptime.TestStrptime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/renne/projects/scrapinghub/dateparser/tests/test_utils_strptime.py", line 62, in test_parsing_date_should_fail_using_datetime_strptime_if_locale_is_non_english
    self.given_system_locale_is('fr_FR.UTF-8')
  File "/home/renne/projects/scrapinghub/dateparser/tests/test_utils_strptime.py", line 14, in given_system_locale_is
    locale.setlocale(locale.LC_ALL, locale_str)
  File "/home/renne/projects/scrapinghub/dateparser/.tox/py36/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

Replacing the locale to any that is installed in my machine (anything from `locale -a` command) made the test pass as expected.

**Comment by rennerocha** [comment]
I am not sure yet :-) Just opened the ticket to avoid forgetting the problem.

**Comment by Gallaecio** [comment]
I think this is expected behavior. Should we improve the error message or the documentation?

**Comment by noviluni** [comment]
This was fixed when we merged this: https://github.com/scrapinghub/dateparser/pull/605
