### ISSUE TITLE
Doesn't install on Python 3.7

### ISSUE THREAD

**Issue by impredicative** [scrapinghub/dateparser#451]
This didn't install for me because the regex requirement failed to install. Is it known to work with Python 3.7?

**Comment by rennerocha** [comment]
Could you share more info about your environment and error messages you are getting?
I installed here in a virtualenv with Python 3.7 in an Ubuntu 16.04 . Probably you are having problems with some of the dependencies, not dateparser itself.

**Comment by impredicative** [comment]
Yes, it's with the `regex` requirement. I'm glad to hear it's working for you, which is all I needed to know.

**Comment by impredicative** [comment]
Fixing this required me to install `python3.7-dev`.
