### ISSUE TITLE
Unexpected result - dateparser is not working for some dateformat

### ISSUE THREAD

**Issue by anoopparampil** [scrapinghub/dateparser#463]
`dateparser.parse('05-11-18', settings={'PREFER_DATES_FROM': 'future'})`

is giving the below output

`datetime.datetime(2118, 5, 11, 0, 0)`

**Comment by trideeprath** [comment]
The problem is here:
https://github.com/scrapinghub/dateparser/blob/master/dateparser/parser.py#L402

Adds/subtracts **100** instead of **1**

**Comment by Gallaecio** [comment]
@anoopparampil What output are you expecting? You are asking to interpret `'05-11-18'` as a date after 2018-11-06 (when you opened this ticket).
