### ISSUE TITLE
Wish list: please add a feature to set the country for the datetime being parsed.  This is much more useful than language or region for narrowing down which timezone is being referred to.

### ISSUE THREAD

**Issue by ismaelharunid** [scrapinghub/dateparser#466]
Wish list: please add a feature to set the country for the datetime being parsed.  This is much more useful than language or region for narrowing down which timezone is being referred to.

Language is helpful generally for months and alphanumeric numbers, articles, etc.. but not helpful in analyzing the timezone or timezone rules of the parsed text.  Locale is more about parsing rules and may have very little to do with the location for the datetime.  In other words if I am in France and using a datetime for my child's birthplace birthplace which is not France, then the timezone abbreviation will be ambiguous
s.  Sure I can use the long timezone code, but users generally won't know those, and sources may not be friendly to that.  Since the parser handles tz abbreviations there needs to be a way to remove or reduce ambiguity.

**Comment by Gallaecio** [comment]
Are you asking for regions (which are country codes) to be taken into account for timezones?
