### ISSUE TITLE
Add a way to get months and week days names

### ISSUE THREAD

**Issue by rominf** [scrapinghub/dateparser#475]
I think of something like this:
```python
dateparser.week_days_names(locale='ru', short=True)
# ['пн', 'вт', 'ср', 'чт', 'пт', 'сб', 'вс']
```

**Comment by Gallaecio** [comment]
I’m not sure this falls within the purpose of this library.

**Comment by noviluni** [comment]
I also think that this library won't be providing this, at least in a short-mid term, so I will close this issue.

If you need to access to the tokens used by `dateparser`, you could do something like this:

```python
>>> from dateparser.data.date_translation_data.ru import info
>>> info.get('tuesday')
['вторник', 'вт']
```
but it's not exactly the same you requested.
