### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by navytux** [scrapinghub/dateparser#494]
Hello up there. First of all I'd like to say thanks for dateparser.

We are using it in [zodbtools](https://lab.nexedi.com/nexedi/zodbtools/merge_requests/8) to parse human-readable times into transaction ID. We found however that the parsing is very slow if the date/time input is invalid and cannot be parsed into a timestamp. This issue was already [reported](https://github.com/scrapinghub/dateparser/issues/426) and somewhat [fixed](https://github.com/scrapinghub/dateparser/pull/428) in 2018. However there is no dateparser version released with the fix.

Since last version of dateparser - v0.7.0 - was released in Feb of 2018 - approximately 1 year ago, it suggests that another release is due by.

So could you please release the next version of dateparser and upload it to PyPI?

Thanks beforehand,
Kirill

/cc @perrinjerome

**Comment by asadurski** [comment]
Thank you! ETA for the release is 12th February.

**Comment by navytux** [comment]
Thanks for feedback, and good luck with releasing.

**Comment by asadurski** [comment]
Version 0.7.1 released (https://github.com/scrapinghub/dateparser/releases/tag/v0.7.1)
Planning for releasing 0.7.2 with pending PRs (no date yet).

**Comment by navytux** [comment]
@asadurski, thanks for making the release.
