### ISSUE TITLE
collections.abc DeprecationWarning - will be deprecated in 3.8

### ISSUE THREAD

**Issue by crunk1** [scrapinghub/dateparser#506]
Getting this warning when running some tests:

> .../python3.7/site-packages/dateparser/date.py:320: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

**Comment by awarecan** [comment]
#471

**Comment by hugovk** [comment]
https://github.com/scrapinghub/dateparser/pull/41 has been merged, this can be closed.
