### ISSUE TITLE
Parse other way: date to "2 weeks ago"

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [scrapinghub/dateparser#517]
Your package can parse things like this `2 weeks ago`.
But could you do the same thing the other way around?

Transform a specific time-delta (now() - paste_date) to such a user-friendly string format like `2 weeks ago`?

**Comment by Gallaecio** [comment]
Going the other way around is out of the scope of dateparser. You might want to use an alternative for that, such as `arrow`, `maya` or `pendulum`.
