### ISSUE TITLE
can be prevent searching relative dates

### ISSUE THREAD

**Issue by Bipulkumarsingh** [scrapinghub/dateparser#525]
I am looking for dates only in my string like 
"25th march 2015 , 26th july 2018 , i need this report today."

I need only dates when search using search.search_dates()
but it also showing today.

Is any way to prevent this.

**Comment by lopuhin** [comment]
The same feature in the ``parse`` function would be great to have as well, or a simple way to tell that the date was relative.

**Comment by Gallaecio** [comment]
May this be a duplicate of #312?

**Comment by noviluni** [comment]
In the last version `0.7.4` this can be done through the `PARSERS` setting. :tada:
