### ISSUE TITLE
Required Date Parts (semi-strict parsing)

### ISSUE THREAD

**Issue by IMP1** [scrapinghub/dateparser#529]
It would be really nice if there was something like `STRICT_PARSING`, but for parts of the date. I'd like to be able to specific to only return dates that have a year and a month, but I don't mind a missing day part.

I haven't had a lot of time to look through the code, but it seems like the only place `STRICT_PARSING` is used is in [`dateparser/parser.py`](https://github.com/scrapinghub/dateparser/blob/master/dateparser/parser.py#L326):

```python
    def _results(self):
        if self.settings.STRICT_PARSING:
            errors = []
            if not self.day:
                errors.append('Day')
            if not self.month:
                errors.append('Month')
            if not self.year:
                errors.append('Year')
            if errors:
                raise ValueError('%s not found in the date string' % ''.join(errors))
```

If this is the *only* place where it's used, and people are happy with this change/addition, I could make up a pull-request sometime soon.

**Comment by noviluni** [comment]
Closed by: https://github.com/scrapinghub/dateparser/pull/703
