### ISSUE TITLE
File base configuration

### ISSUE THREAD

**Issue by Allactaga** [scrapinghub/dateparser#54]
`Settings` object [here](https://github.com/scrapinghub/dateparser/blob/648787eb39267d7a681f6a135c8ea442545b0d52/dateparser/conf.py#L5) must be able to get settings file on initialization (string or already opened file) and defaults to `data/settings.yaml` if not set. All settings should be moved to this file instead of class attributes. Here is [how it is done](https://github.com/scrapinghub/dateparser/blob/03ec8be1f31a7fb08f5b28da7be2e752b92ac4f5/dateparser/languages/loader.py#L34) for `LanguageDataLoader` class.

There could be some additional notes for improvement of existing code when pull-request is ready.

**Comment by MojoJolo** [comment]
@Allactaga I think I can handle this. I'll study the code and get back on this issue.

**Comment by MojoJolo** [comment]
Pull request here: https://github.com/scrapinghub/dateparser/pull/93

**Comment by waqasshabbir** [comment]
Done #93
