### ISSUE TITLE
Timestamp in milliseconds with minus (-) - parsing failes/returns None

### ISSUE THREAD

**Issue by Salfiii** [scrapinghub/dateparser#546]
Hi,

**Version**:
dateparser==0.7.1

parsing a timestamp in milliseconds with an minus in front of it, returns None.

**Example**:
>> dateparser.parse("-186454800000")
>> None

The correct date would be:
Feb 03 1964 23:00:00

If I remove the minus or pass any other positive timestamp in milliseconds, everything works as expected, so it´s definetly the minus. 
I obviously can´t remove it, because it will return a wrong datetime value.

Converter for timestamp in milliseconds:
https://currentmillis.com/

Thanks and best regards

**Comment by noviluni** [comment]
It would be really nice to add support for negative timestamps, but we should handle some side effects.

For example, the timestamps for:  `1969-12-31 23:59:59` is `-1` (and in milliseconds is:  `-1000`). Obviously, this would raise a lot of false positives every time we find a negative number. However, we could create a separate, optional, parser called `negative-timestamp` and allow users to activate it if they need it. We could mention it in the docs near the `timestamp` parser.

**Comment by Gallaecio** [comment]
I believe what @noviluni describes is to make a separate parser just to support negative numbers, and *not* make it a part of the default value of the `PARSERS` setting. Instead, we document the existence of the parser, so that users may add it to their `PARSERS` setting if they so wish.
