### ISSUE TITLE
Better period extracting from dateutil parser

### ISSUE THREAD

**Issue by Allactaga** [scrapinghub/dateparser#55]
As we now have information of what date units (year, month, hour) [were parsed exactly](https://github.com/scrapinghub/dateparser/blob/c0b7340bb7e4f670c876d5d3e8863ffe5afcf8db/dateparser/date_parser.py#L51) by dateutil parser, we now can guess date period with more precision. For example, if any of the `day`, `hour`, `minute`, `second`, `microsecond` units were parsed, then it is `day` period, else if `month` was parsed then period is `month` and at last `year` period for `year` unit. I am not sure if `week` period can be applicable to dates passed to dateutil parser.

This period should be passed all the way back to call from `_DateLanguageParser`.

**Comment by waqasshabbir** [comment]
Fixed in #59
