### ISSUE TITLE
Should have a 'zero' option for incomplete dates

### ISSUE THREAD

**Issue by ilienert** [scrapinghub/dateparser#553]
Instead of forcing some default day of the month for incomplete dates, it would be very helpful if you could zero out the day so you'd know what part of the date string was missing.

Example:
```
parse(u'December 2015', settings={'PREFER_DAY_OF_MONTH': 'zero'})
>>> datetime.datetime(2015, 12, 0, 0, 0)
```
The same behaviour should be available for years, months, etc.

**Comment by waltertross** [comment]
Unfortunately that would be an invalid datetime (if you try to create it, you get "ValueError: day is out of range for month")
There should be another way of signalling whether date, time or both were set in each datetime. I think that with an option in settings one should be able to request an extra member of the output tuples carrying this information.

**Comment by noviluni** [comment]
Just added a PR trying to find a solution for this: https://github.com/scrapinghub/dateparser/pull/729

Please, if you have any feedback let me know.

**Comment by noviluni** [comment]
We can't provide incomplete dates, but we can give more context by using `DateDataParser()` and `get_date_data()` as explained in this comment: https://github.com/scrapinghub/dateparser/issues/700#issuecomment-734326956


So I will close this issue in favor of the other as it's pointing to the correct solution we will work on in the future. 

Thanks for the feedback :)
