### ISSUE TITLE
If we pass invalid string to dateparser.parse() it's taking very log time

### ISSUE THREAD

**Issue by prudentia** [scrapinghub/dateparser#564]
I found this problem while i using dateparser.parse(), if some invalid string is given its taking really long time.

=========== ==========

import dateparser

a = 100
while a!=0:
    a-=1
    b = dateparser.parse("")

It took 12 seconds

===================

import dateparser

a = 100
while a!=0:
    a-=1
    b = dateparser.parse("my name is not taj")

It took 18 seconds

**Comment by Jefffish09** [comment]
@prudentia Agree!

If pass some invalid content to dateparser.parse(), some cases will cost very very long time. I think it need a parameter like "timeout" to skip( or return error)  these cases if parse for a long time.

**Comment by noviluni** [comment]
Hi @prudentia @Jefffish09 

We did some performance improvements in the last released version (`0.7.4`) and now the first case needs less than 1 second and the second case 3 seconds.

I think this result is quite better (and acceptable, as we are parsing 100 invalid dates and when parsing invalid dates `dateparser` needs to try all the possible different options). 

Could you test again with the last released version `0.7.4`?

I think that we can close this issue if you agree.

**Comment by Jefffish09** [comment]
@noviluni Thanks!
