### ISSUE TITLE
dateparser.parse returns None for any datetime using 24hr format and time period when hour is > 12

### ISSUE THREAD

**Issue by klmunday** [scrapinghub/dateparser#571]
Whils't parsing some data I got an error when processing `Sep 28, 2016, 20:13 pm`, I believe this is due to a conflict between 24 hour time format and a time period being supplied.
```
>>> print(dateparser.parse('Sep 28, 2016, 12:13 PM'))
2016-09-28 12:13:00
>>> print(dateparser.parse('Sep 28, 2016, 11:13 PM'))
2016-09-28 23:13:00
>>> print(dateparser.parse('Sep 28, 2016, 13:13 PM'))
None
>>> print(dateparser.parse('Sep 28, 2016, 13:13 AM'))
None
>>> 
```
I know this isn't technically valid since the period is not needed with 24hr format. Instead of returning `None` I believe that it would be useful to instead just ignore the given period and fallback on the given 24hr format.

i.e.:
`Sep 28, 2016, 13:13 AM` -> `Sep 28, 2016, 13:13`
`Sep 28, 2016, 13:13 PM` -> `Sep 28, 2016, 13:13`

**Comment by Gs-001** [comment]
Hey @Gallaecio @klmunday  , I have added a PR to handle this case.
Please have a look and ping me if any changes are required.
