### ISSUE TITLE
Why I tried dateparser.parse and return the wrong result

### ISSUE THREAD

**Issue by li1201** [scrapinghub/dateparser#583]
I tried to use dateparser to convert the time but got the wrong result. Below is what I tried:

dateparser.parse('07:00 PM PST, November 02, 2019', settings={'TO_TIMEZONE': 'Asia/Taipei'})

It should returns: datetime.datetime(2019, 11, 3, 10, 0, tzinfo=<DstTzInfo 'Asia/Taipei' CST+8:00:00 STD>)

But I got this return: datetime.datetime(2019, 11, 3, 11, 0, tzinfo=<DstTzInfo 'Asia/Taipei' CST+8:00:00 STD>)

Can anyone help me to resolve this wired problem? Thanks a lot!

**Comment by Gallaecio** [comment]
According to https://www.worldtimebuddy.com/pst-to-taiwan-taipei the difference is +16h.

07:00 PM + 16h = 11:00 AM

Can you please confirm that the actual result is as expected, or provide some source that supports your claim?

**Comment by li1201** [comment]
Hello Gallaecio,

I think that I probably did some wrong calculation at that time. Anyway, I have no problem now. Thanks for your comment.
