### ISSUE TITLE
The execution produced incorrect results

### ISSUE THREAD

**Issue by 7134g** [scrapinghub/dateparser#606]
from dateparser import parse

print(parse('20110101'))

result:
1010-02-01 01:00:00

**Comment by Gallaecio** [comment]
```
>>> dateparser.__version__
'0.7.2'
```

**Comment by 7134g** [comment]
The version I'm using right now is 0.7.2

**Comment by noviluni** [comment]
What is happening here is that by default, the `DATE_ORDER` variable in setting is `MDY`.

So this `1010-02-01` is interpretated in this way: `2-01-1010-1` (month-day-year-hour).

I suspect that what you expected to get is 2011-01-01. You can get it by using:

```python
dateparser.parse('20110101', settings={'DATE_ORDER': 'YMD'}) 
>>> datetime.datetime(2011, 1, 1, 0, 0)
```

In this cases, where there are no spaces or symbols between the years, months and days it is impossible to do it better if you don't specify the preferred `DATE_ORDER`.

@7134g  @Gallaecio  What do you think? Do you still think it's a bug?

**Comment by 7134g** [comment]
thank you

but, I was able to parse the correct results using dateutil.

I looked at the requirements.txt content and it's true that there is a dependency on the package content of dateutil, but I'm not sure if it's entirely based on this secondary development.

>>>from dateutil.parser import parse
>>>parse('20110101')
datetime.datetime(2011, 1, 1, 0, 0)

That's what I want.
But, thanks for the answer, it was helpful
@noviluni

**Comment by noviluni** [comment]
Good to know it was useful! I will close the issue, but if you need something don't hesitate to open it again.

**Comment by Gallaecio** [comment]
I still think that, without parameters, dateparser should return the expected date. But I guess it would be more of an improvement request than a bug report.

**Comment by 7134g** [comment]
So, in the end, I didn't use the method he provided, because the format of my variable values was not fixed, so I had to match through regular expressions before using dateparser.
I still hope that the next version will modify this matching rule.

**Comment by 7134g** [comment]
> I still think that, without parameters, dateparser should return the expected date. But I guess it would be more of an improvement request than a bug report.

So, in the end, I didn't use the method he provided, because the format of my variable values was not fixed, so I had to match through regular expressions before using dateparser.
I still hope that the next version will modify this matching rule.
