### ISSUE TITLE
milliseconds

### ISSUE THREAD

**Issue by zakarianamikaz** [scrapinghub/dateparser#610]
hello,
when i'm parsing dates
dateparser.parse(u'now',) ==>2020-01-15 00:50:47.533726
expected  result 2020-01-16 05:50:47
how can i do it !
thanks

**Comment by noviluni** [comment]
Hi @zakarianamikaz 

What you are requesting is neither an issue or a bug, it is a question. Please use the "dateparser" tag at [StackOverflow](https://stackoverflow.com/tags/dateparser) to ask for help.

P.S.: You can also check the Python docs to know how to format `datetime` objects using `strftime`.
