### ISSUE TITLE
`SUPPORT_BEFORE_COMMON_ERA` declared but not working

### ISSUE THREAD

**Issue by noviluni** [scrapinghub/dateparser#613]
I was curious about this setting and I found only two references: https://github.com/scrapinghub/dateparser/search?q=SUPPORT_BEFORE_COMMON_ERA

It seems that this setting was added here: https://github.com/scrapinghub/dateparser/commit/02d525107abcfe720b6495df8d8a1eb9028d7930 as an example/proposal (https://github.com/scrapinghub/dateparser/issues/35) but it has never been implemented.

I think we should remove it from the codebase to avoid confusions and add it again when developing it.

**Comment by lucasdutraf** [comment]
Hey there!
Is anyone working on this issue @noviluni ? If there is no one I could work on it.

**Comment by noviluni** [comment]
@lucasdutraf go ahead, please! :smile:
