### ISSUE TITLE
Unable to parse UTC / GMT >= 10

### ISSUE THREAD

**Issue by craigmaloney** [scrapinghub/dateparser#615]
Noticing a bug where GMT-10 is not parsing, but GMT-5 is:

```
>>> dateparser.parse("Thu Feb 06 2020, 04:00:00 GMT-5")
datetime.datetime(2020, 2, 6, 4, 0, tzinfo=<StaticTzInfo 'UTC\-05:00'>)
>>> dateparser.parse("Thu Feb 06 2020, 04:00:00 GMT-10")
>>>
```

It appears that double-digit parsing isn't supported:

```
>>> dateparser.parse("Thu Feb 06 2020, 04:00:00 GMT-9")
datetime.datetime(2020, 2, 6, 4, 0, tzinfo=<StaticTzInfo 'UTC\-09:00'>)
>>> dateparser.parse("Thu Feb 06 2020, 04:00:00 GMT-11")
>>> dateparser.parse("Thu Feb 06 2020, 04:00:00 GMT-12")
>>> dateparser.parse("Thu Feb 06 2020, 04:00:00 GMT-12")
```

If it's converted to UTC-10:00 it does parse:
```
>>> dateparser.parse("Thu Feb 06 2020, 04:00:00 UTC-10:00")
datetime.datetime(2020, 2, 6, 4, 0, tzinfo=<StaticTzInfo 'UTC\-10:00'>)
```

**Comment by aditya-hari** [comment]
Hello, I would like to try and solve this issue. Which files should I be looking at to see what might be going wrong?

**Comment by aditya-hari** [comment]
@Gallaecio  
 
Okay so this issue is because of incorrect regex patterns. I will be able to solve this soon.

**Comment by grestonian** [comment]
@craigmaloney @Gallaecio I've applied this fix to parse double digits for timezones. Please let me know if you find any anomalies.

**Comment by grestonian** [comment]
@noviluni @Gallaecio there was one test case in the source code:
`'Fri Sep 23 2016 10:34:51 GMT+0800 (CST)'`

What is the expected output for this input case?

**Comment by Gallaecio** [comment]
If you mean because of the `(CST)` at the end, my guess is that the string should be interpreted the same as it would without it.
