### ISSUE TITLE
Doc MDY/DMY detection issue (incoherence? error?)

### ISSUE THREAD

**Issue by buriy** [scrapinghub/dateparser#617]
DateParser Documentation, Release 0.7.2
3.3 OOTB Language Based Date Order Preference
>>> # parsing ambiguous date
>>> parse('02-03-2016') # assumes english language, uses MDY date order
datetime.datetime(2016, 3, 2, 0, 0)
>>> parse('le 02-03-2016') # detects french, uses DMY date order
datetime.datetime(2016, 3, 2, 0, 0)

**Comment by noviluni** [comment]
Hi @buriy !

Yeah, that's an error. The first case should return `datetime.datetime(2016, 2, 3, 0, 0)`. You can open a new PR if you want. :)

Thanks for raising it!

**Comment by lucasdutraf** [comment]
If anyone is not currently working on it, I could!

**Comment by lucasdutraf** [comment]
I´ve created a pull request that fixes this issue at #619
