### ISSUE TITLE
time dot as delimiter

### ISSUE THREAD

**Issue by dadosch** [scrapinghub/dateparser#643]
Currenty, only time with a ":" as delimiter is supported not with a "."

**Comment by Gallaecio** [comment]
Could you share links to real life examples? They can be used to reproduce the issue and for test-driven development.

**Comment by dadosch** [comment]
I have here the link of THE german dictionary on how to write times in german (in german, obviously), you can see a example with the dot there: https://www.duden.de/sprachwissen/sprachratgeber/Uhrzeitangaben

> Der Doppelpunkt kann auch durch einen Punkt ersetzt werden: 8.03 Uhr
(The colon can also be replaced by a dot: 8.03)

The original website I first saw this today isn't stable enough to use for test-driven development (a local district's page of corona cases), so I will give some examples: (also for the search part)

"23. März 18.37 Uhr" => 2020-03-23 18-37-00
"29.02.2020 13.12" => 2020-02-29 13-12-00

**Comment by Gallaecio** [comment]
```python
>>> dateparser.__version__
'0.7.4'
>>> dateparser.parse("23. März 18.37 Uhr")
>>> dateparser.parse("29.02.2020 13.12")
>>> 

```

**Comment by XtremeGood** [comment]
Is this expected behaviour or a bug?
![image](https://user-images.githubusercontent.com/40588378/77843943-945c7180-71bf-11ea-805e-161a52de6ac7.png)

**Comment by Gallaecio** [comment]
@XtremeGood Please, do not use screenshots for things that can be represented as text.

Also, I’m not sure that the issue depicted by your screenshot is exactly the same as the one described in this issue, so a new ticket may be better assuming there is not already a different, matching issue open.
