### ISSUE TITLE
Indented def?

### ISSUE THREAD

**Issue by jgtimestuff** [scrapinghub/dateparser#644]
This might be nothing, but I was wondering why the def for apply_time is indented inside the def for parse in freshness_date_parser.py?   

      def apply_time(dateobj, timeobj):
            if not isinstance(_time, time):
                return dateobj

            return dateobj.replace(
                hour=timeobj.hour, minute=timeobj.minute,
                second=timeobj.second, microsecond=timeobj.microsecond
            )

**Comment by Gallaecio** [comment]
https://realpython.com/inner-functions-what-are-they-good-for/

**Comment by jgtimestuff** [comment]
Thanks.
