### ISSUE TITLE
Text "are" returning a datetime object

### ISSUE THREAD

**Issue by gogaurav** [scrapinghub/dateparser#645]
from dateparser.search import search_dates

search_dates("are")
[('are', datetime.datetime(2020, 3, 22, 0, 0))]

dateparser.__version__
'0.7.4'

**Comment by heraclex12** [comment]
It is a correct anwser.
When I try to debug,  I see "are" word is mapping "sunday" in "saq" language (I don't know this language).
So It's not a bug.

**Comment by gogaurav** [comment]
Yeah. not a bug. I didn't observe that we can pass the language also as an argument. When I am passing English, nothing returns.
