### ISSUE TITLE
Dateparser: Memory Leak 

### ISSUE THREAD

**Issue by kkoehncke** [scrapinghub/dateparser#666]
Hi! 

I've been working with dateparser in a web service application and recently have been seeing a memory leak where RAM consumption has continually increased as the service processes inbound requests. After doing some digging around, tracemalloc shows the following:

```
dateparser/languages/dictionary.py:213: size=260 MiB (+260 MiB), count=4491080 (+4491080), average=61 B
dateparser/languages/dictionary.py:184: size=129 MiB (+129 MiB), count=112281 (+112281), average=1207 B
dateparser/languages/locale.py:385: size=79.8 MiB (+79.8 MiB), count=699384 (+699384), average=120 B
dateparser/conf.py:50: size=61.7 MiB (+61.7 MiB), count=112276 (+112276), average=576 B
dateparser/languages/dictionary.py:214: size=48.7 MiB (+48.7 MiB), count=112280 (+112280), average=455 B
dateparser/languages/locale.py:380: size=14.8 MiB (+14.8 MiB), count=215570 (+215570), average=72 B
```

Looking at the source code, I see these five dictionaries defined in dictionary.py:
```
    _split_regex_cache = {}
    _sorted_words_cache = {}
    _split_relative_regex_cache = {}
    _sorted_relative_strings_cache = {}
    _match_relative_regex_cache = {}
```

Would there be a way for the caller to invalidate or disable this caching mechanism?

**Comment by Gallaecio** [comment]
Assuming you are already using the latest stable version, could you try using the `master` branch of `Dateparser`, see if you can reproduce the issue with it?
