### ISSUE TITLE
DATE_ORDER is not taken into account in version 0.7.2+

### ISSUE THREAD

**Issue by vanaoff** [scrapinghub/dateparser#690]
OS: Linux (tested on Ubuntu and Manjaro)
Python: Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
Affected versions: `dateparser>=0.7.2`
Steps to reproduce the problem:
```python
import dateparser

settings = {'DATE_ORDER': 'MDY', 'PREFER_LANGUAGE_DATE_ORDER': False}
dateparser.parse('le 02-03-2016', settings=settings)
```
Expected result: `datetime.datetime(2016, 2, 3, 0, 0)`
Actual result: `datetime.datetime(2016, 3, 2, 0, 0)`

**Comment by noviluni** [comment]
Hi @vanaoff, thank you for reporting this. 

This is not affecting the master branch, so it should be fixed as soon as we release a new version.

**Comment by noviluni** [comment]
Related to this: https://github.com/scrapinghub/dateparser/issues/589

**Comment by noviluni** [comment]
@vanaoff I will try to release a new version this month and I will try notify you. Thank you again!

**Comment by vanaoff** [comment]
Thanks!
