### ISSUE TITLE
Weird behavior when adding a trailing space

### ISSUE THREAD

**Issue by noviluni** [scrapinghub/dateparser#691]
When using this expression I don't get any result:
```python
>>> dateparser.parse('午前10時')
```

However, when adding a trailing space I get a value:
```python
>>> dateparser.parse('午前10時 ')
datetime.datetime(2020, 5, 19, 0, 17, 52, 777714)
```

**Comment by noviluni** [comment]
I think this is because of the Regex. However, I'm not sure if the first example should return a value or if the second shouldn't return it. Better Japanese skills would help here.

BTW, I'm surprised that the "sanitize" function doesn't delete the trailing spaces.

**Comment by Gallaecio** [comment]
Google says it’s “10 am”. Which, if accurate, would mean that none of the parsings is correct. And the second parsing is worse, as it is returning an incorrect date.

**Comment by noviluni** [comment]
Since we merged this: https://github.com/scrapinghub/dateparser/pull/841 the original issue won't happen again and we can close this ticket. 

We could open a new ticket regarding the language issue, but I don't have enough Japanese knowledge to ever know if it's correctly formed or not, so I will just close it. Feel free to open a new language-issue.
