### ISSUE TITLE
Option to set base date in case of relative dates?

### ISSUE THREAD

**Issue by KaustavPurkait** [scrapinghub/dateparser#694]
Is it currently possible to set a base date when calculating relative dates?

For example, 2 weeks later currently is parsed to 2 weeks from local time, but in case of an article which was written on a specific date, it would make more sense for the result to get parsed into 2 weeks from the given base date.

**Comment by KaustavPurkait** [comment]
Figured it out. Closing the issue.

**Comment by rth** [comment]
> Figured it out. Closing the issue.

It's good to indicate what was the solution you found for other readers. In this case it was likely setting `RELATIVE_BASE` option.
