### ISSUE TITLE
tox is not in tests/requirements.txt

### ISSUE THREAD

**Issue by eamanu** [scrapinghub/dateparser#697]
Hi everybody, 

According to the contributing page [0] I need to run this to test:

```
$ pip install -r tests/requirements.txt # install test dependencies
$ pip install -r scripts/requirements.txt # install script dependencies
$ flake8 dateparser tests
$ tox
```
But, tox is not in the test/requirements.txt. So, I cannot run the above 
commands directly, because assume that tox is installed.

IMHO tox module must be added into tests/requirements.txt 

[0] https://github.com/scrapinghub/dateparser/blob/master/CONTRIBUTING.rst

**Comment by Gallaecio** [comment]
The documentation is wrong, you should just run `tox` there, and it will perform all the 3 previous steps on its own.

Also, `tox` should not be in any requirements file, and should instead be installed manually. So maybe we should add `pip install tox` to those instructions.

**Comment by eamanu** [comment]
Hi @Gallaecio, good point. Please consider review the PR: https://github.com/scrapinghub/dateparser/pull/698. I mention on the documentation the installation of tox.
