### ISSUE TITLE
Intended PyPI update?

### ISSUE THREAD

**Issue by rrb5068** [scrapinghub/dateparser#70]
Current PyPI release (0.1.0) is from November 2014. With the latest changes on here, I've found much better accuracy with hours, minutes, and seconds. Do you have an intended date for the next release? This is a really great library.

**Comment by Allactaga** [comment]
Hi @rrb5068 , sorry for it took for me too long to respond. We have hands tied up with some other work outside this module atm, but we'll try to squeeze a new version by the end of this month.

No promises though, but we really really try :smiley:

**Comment by dangra** [comment]
ping for pypi release :)

**Comment by Allactaga** [comment]
We've already merged everything that was required for new version, except updated documentation. As you know, we had rough time with our client's project so we'll get back to documentation in a calmer times :)

**Comment by Allactaga** [comment]
Hi @rrb5068, we've just uploaded `v0.2.0` version of `dateparser` to pypi. It's a version of consistency where code, tests and documentation are in sync. From here we'll work on `v0.2.1` fix build and later on `v0.3.0` and so on. We hope that now, when we have got our codebase in order with tests and documentation it would be easier to release new version at any given point :smiley:

**Comment by Allactaga** [comment]
We've released `v0.2.1` couple of days ago.

**Comment by dangra** [comment]
:+1:
