### ISSUE TITLE
Latest release creates namespace conflict for scripts directory

### ISSUE THREAD

**Issue by charbz** [scrapinghub/dateparser#705]
it looks like the dateparser pip package creates a namespace conflict for scripts directory.
So any project containing a scripts module in its root directory will no longer be able to use it.

**Example Project Directory:**
- env/
- scripts/
     - foo/
          - bar.py

if you install dateparser `pip install dateparser` and you run your script: `python -m scripts.foo.bar`

**you get error:**
`Error while finding module specification for 'scripts.foo.bar' (ModuleNotFoundError: No module named 'scripts.foo')`

but when you uninstall dateparser `pip uninstall dateparser`

**No namespace confict:**
`python -m scripts.foo.bar`
`foo bar`

**Comment by noviluni** [comment]
Hi @charbz, thank you for reporting this, I will try to release a fix as soon as possible.

**Comment by noviluni** [comment]
Hi @charbz @seanwendt @CB-GuangyaoXie, we have just released a new version (v0.7.6) fixing this.


Thank you for raising it!

**Comment by charbz** [comment]
Thanks for the quick fix @noviluni

**Comment by musicinmybrain** [comment]
Do these scripts need to be included in binary distributions (e.g. wheels) and installed in `site-packages` at all? Or would it be better to exclude them in the call to `find_packages()` in `setup.py`?
