### ISSUE TITLE
Usage of 'next' and 'last' with weekdays

### ISSUE THREAD

**Issue by mrj1m0thy** [scrapinghub/dateparser#716]
Would love to see the ability to get dates for "next monday", "last monday" and other similar usages.

**Comment by noviluni** [comment]
Hi @mrj1m0thy!

There is an open PR that tries to implement it but it's not finished: https://github.com/scrapinghub/dateparser/pull/638

I also would love to have it, so I will try to push to add it in the next release.

Cheers!

closed as duplicated of this: https://github.com/scrapinghub/dateparser/issues/573
