### ISSUE TITLE
Delete requirements.txt and remove references to Scrapy Cloud

### ISSUE THREAD

**Issue by noviluni** [scrapinghub/dateparser#724]
~~While the requirements in `test/requirements.txt` and `dateparser_scripts/requirements.txt` are generic (no version pinning), the requirements in the `requirements.txt` are pinned. I think we could update them to the last versions and, if it's possible, unpin them.~~

We should delete the `requirements.txt` file and the documentation section that refers to how to deploy the library to the Scrapy Cloud.

**Comment by Gallaecio** [comment]
What’s the use case of `requirements.txt`? Maybe we can remove it.

**Comment by kishan3** [comment]
@Gallaecio It is used here 
https://github.com/scrapinghub/dateparser/blob/master/docs/installation.rst#deploying-from-latest-sources 

do we still need it?

**Comment by noviluni** [comment]
Hi @kishan3 

* Short answer: No
* Long answer: We need to delete the file but also that part from the documentation as it doesn't have any sense right now. It was first raised here: https://github.com/scrapinghub/dateparser/issues/397#issuecomment-428322785 So if you want you can work on it. :)
