### ISSUE TITLE
Deprecate Python 2.7

### ISSUE THREAD

**Issue by noviluni** [scrapinghub/dateparser#727]
As part of the next version 1.0.0 we will deprecate Python 2.7. I have just created this ticket to track it.

- [X] Merge as more finished PRs as possible (to avoid future file conflicts)
- [X] Change tox and Travis to test only with Python 3. (ref: https://github.com/scrapinghub/dateparser/pull/744)
- [x] Change the setup file. (ref: https://github.com/scrapinghub/dateparser/pull/755)
- [x] Apply 2to3 and review carefully (`__future__` imports, unicode strings...) (ref: https://github.com/scrapinghub/dateparser/pull/748)
- [x] Remove six package (ref: https://github.com/scrapinghub/dateparser/pull/754)
- [x] Remove utf declaration strings (ref: https://github.com/scrapinghub/dateparser/pull/758, #761, #764)
- [x] Check specific code for Python 2 that can be removed or refactored (https://github.com/scrapinghub/dateparser/pull/763, https://github.com/scrapinghub/dateparser/pull/749, https://github.com/scrapinghub/dateparser/pull/777)
- [x] Check and update docs and comments (https://github.com/scrapinghub/dateparser/pull/783)

**Comment by kishan3** [comment]
Hi @noviluni Is it possible to list tasks we need to do perform deprecation?
Or we just need to check it file by file?

**Comment by noviluni** [comment]
Hi @kishan3, we have some pending PRs labeled as `breaking-change` (https://github.com/scrapinghub/dateparser/labels/breaking-change) that I'm waiting to merge after seeing that this last release is stable enough. If we don't see any major issue raised before the 15th of July, we will merge those PRs and after that starting to migrate the library to Python 3 code (deprecating Python 2.7).

My idea is to:
* Merge as more finished PRs as possible (to avoid future file conflicts)
* Change tox and Travis to test only with Python 3.
* Change the setup file.
* Proceed with code changes.

From my experience, the best way to proceed is by using the `2to3' library (reviewing manually each change as some things are not always necessary). After that, we will remove the `six` package, remove the utf strings and check if there are specific code for Python 2 or Python 3 that can be removed or refactored.

To avoid really big PRs, I think that we could start by using 2to3 in some specific sections (for example in tests, in scripts, etc.).

**Comment by noviluni** [comment]
Today is 15th, so we can start with the migration :muscle: 

I will spend some time merging PRs marked as "breaking change" to avoid too many conflicts when removing Python 2 reminiscents.

**Comment by noviluni** [comment]
Today is the 15th and no big issues have been raised so far, so we can start deprecating Python 2! :muscle: 

I finished merging some PRs with breaking changes that were waiting. Now we can proceed with deleting the Python 2 and PyPI environments from tox and Travis.

**Comment by noviluni** [comment]
After merging my last two PRs, I think I can say that we have successfully migrated the package to Python 3 only. :muscle: 

I will proceed by closing this issue.

Thanks @kishan3  and @Gallaecio for your support :)
