### ISSUE TITLE
Not compatible with tzlocal 3.0b1

### ISSUE THREAD

**Issue by washeck** [scrapinghub/dateparser#791]
`tzlocal 3` switched to from `pytz` to `zoneinfo` from Python 3.9 (or `backports.tzinfo` for older Pythons) and `dateparser` now crashes with

```
.../lib/python3.8/site-packages/dateparser/date_parser.py", line 37, in parse
    date_obj = stz.localize(date_obj)
AttributeError: 'backports.zoneinfo.ZoneInfo' object has no attribute 'localize'

```

dateparse should either restrict the required `tzlocal` version to <3 or fix the compatibility `zoneinfo.ZoneInfo` objects.

**Comment by noviluni** [comment]
Hey @washeck, thank you for raising this up!

I added a PR adding compatibility with both versions. #792

**Comment by spovich** [comment]
I just ran into this with a python 3.8 project using dateparser 0.7.6.  By adding `tzlocal==2.1` as an explicit dependency, I was able to work around the error.  Look forward #792 landing and release! Thanks!
