### ISSUE TITLE
Wrong parsing with Italian date format

### ISSUE THREAD

**Issue by DarkSkull91** [scrapinghub/dateparser#809]
I noticed when I try do parse a date string like this `mar 5 set 2017, 7:52` with this piece of code:
`dateparser.parse("mar 5 set 2017, 7:52", date_formats=["%a %d %b %Y, %H:%M"], languages=["it"])`
Parser returns a `NoneType`, it seems it's happend only with `mar` (martedì) which means tuesday. With all other weekdays it works.

**Comment by noviluni** [comment]
Hi @DarkSkull91, thank you for opening this issue. This is a known bug that should be handled in the future versions: 
https://github.com/scrapinghub/dateparser/issues/676

As there is another open issue (https://github.com/scrapinghub/dateparser/issues/337) with the same example I will close this.

If you have any idea about how to fix it you can comment on those issues with your ideas.

Thanks
----

Closed as duplicated of https://github.com/scrapinghub/dateparser/issues/337
