### ISSUE TITLE
STRICT_PARSING bug

### ISSUE THREAD

**Issue by kensouchen** [scrapinghub/dateparser#816]
```python

dateparser.parse("22", settings={"STRICT_PARSING": True})
# datetime.datetime(1900, 1, 1, 2, 2)
```

failed to handle this case.

**Comment by noviluni** [comment]
Hi @kensouchen, thank you for opening this issue. This is fixed in master and will be fixed in the next version, that will be released this week.

I will close this issue, feel free to open it again if you need it.
