### ISSUE TITLE
Unable to generate en.py

### ISSUE THREAD

**Issue by NEERAJAP2001** [scrapinghub/dateparser#817]
reference comment: https://github.com/scrapinghub/dateparser/pull/812#issuecomment-712714740

@noviluni sir, in that Process, I had to generate ```en.py```, but I'm getting this error :  

command: ```python write_complete_data.py```

Error : 

```Traceback (most recent call last):
  File "write_complete_data.py", line 113, in <module>
    write_complete_data()
  File "write_complete_data.py", line 93, in write_complete_data
    date_translation_data = _get_complete_date_translation_data(language)
  File "write_complete_data.py", line 54, in _get_complete_date_translation_data
    cldr_data = json.load(f, object_pairs_hook=OrderedDict)
  File "C:\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 195: character maps to <undefined>
```

**Comment by noviluni** [comment]
Hi @NEERAJAP2001, could you submit the current code you have in a PR so I will be able to see the code? It's impossible for me to know the error without looking at the code.

If the work is still in progress you can add "WIP:" to the PR title or open it as a "Draft PR".

**Comment by NEERAJAP2001** [comment]
Yes, sir #821 is the code !!
