### ISSUE TITLE
Search text for dates

### ISSUE THREAD

**Issue by shaneaevans** [scrapinghub/dateparser#82]
It would be useful for Portia if it is possible to search text for dates, see https://github.com/scrapinghub/portia/issues/192

**Comment by Allactaga** [comment]
We had this in early days of `dateparser` but this was greatly interfering with ability to properly work not only with English dates but with other languages (especially with languages without word spacing, like Chinese). `dateparser` is in the first place multilingual library which focus on parsing **valid** dates in any language.

**Comment by Allactaga** [comment]
We will try to target this issue in later (much later) versions. Until then this would stay open for discussion. 

Another thing with fuzzy parsing was that it was parsing invalid dates like `Aug 7, 2014Aug 7, 2014` (resulting in `datetime(2007, 8, 7, 20, 14)`). So we should approach this carefully.

**Comment by solalatus** [comment]
I have tried to do something alike: detect multiple dates in a string.
NOT YET TESTED, but seems working.
It might help...
`import dateparser

def detect_date(line=""):
    """Detect multiple, multi language date and datetime entries in a given string.

    @param type: String to detect occuring_dates in, ideally a single line.
    @type type: String
    @return: Returns the list of found DateTime objects or None
    @rtype: List or None
    """

    # For a start, split the string, remove , and ; to get rid of edge cases
    # and be able to manipulate the data word by word
    splitted_line=line.replace(",","").replace(";","").split()

    occuring_dates=[]
    broken=False
    i=0
    j=len(splitted_line)+1

    while i<len(splitted_line)-1:
        while j>=0:
            #Generate a candidate combination of words
            section=" ".join(splitted_line[i:j])

            try:
                #If the input string is really not vaild, dateparser will raise an exception.
                date=dateparser.parse(section)
                if date==None:
                    #If dateparser returns with None, raise an exception.
                    raise Exception("No date could be parsed.")
                else:
                    #If we found something, just store it.
                    occuring_dates.append(date)

            except:
                #Nothing has been found, go ahead...
                j-=1
            else:
                #We have found something, hopefully
                if date:
                    #Update the original list, remove everything "covered" by what we found.
                    #This is the way to get rid of duplicates from parsing parts
                    # of the same datetime many times.
                    splitted_line=splitted_line[j+1:]
                    i=0
                    broken=True
                break

        j=len(splitted_line)+1
        if not broken:
            i+=1

    #This is a "detector", so give None if nothing is found, so as to fit in logical operations.
    if occuring_dates==[]:
        occuring_dates=None

    return occuring_dates

if __name__ == '__main__':

    #English dummy example
    line="aaa Sat, 16 Jul 2016 06:09:12 +0000 and Sat, 17 Aug 2015 09:11:15 +0100 aaa and 2 days ago aaaaa"
    results=detect_date(line)
    for r in results:
        print(r)`

**Comment by divyanshshukla13** [comment]
Hi all.
I am hoping to work  on this idea for GSoC. 
I was thinking that for a given body of text, first recognise it's language and then construct a regex 
to match the required string. 
The above example from @solalatus uses all possible combination of tokens(say given n of them in a string) and results in O(n<sup>2</sup>) while regex can do the job in O(n). 
The above idea has already been implemented by '[akoumjian/datefinder](https://github.com/akoumjian/datefinder)'  and can be used as an inspiration.

**Comment by asadurski** [comment]
Resolved with https://github.com/scrapinghub/dateparser/pull/324 :tada:
