### ISSUE TITLE
Numbers are parsed as time despite `STRICT_PARSING=True`

### ISSUE THREAD

**Issue by herleswarna** [scrapinghub/dateparser#835]
1. It is subjective but I don't think `23` should be parsed to 2:03
2. Strict parsing should reject such result because of missing year, month, day, but it doesn't

```
>>> import dateparser
>>> dateparser.parse('23', languages=['de'], settings={"STRICT_PARSING": True, "PARSERS": ["absolute-time"]})
datetime.datetime(1900, 1, 1, 2, 3)
```

**Comment by noviluni** [comment]
Hi @herleswarna , what version are you using?

This was fixed in the last version (`dateparser==1.0.0`):

```python3
>>> import dateparser

>>> dateparser.parse('23', languages=['de'], settings={"STRICT_PARSING": True, "PARSERS": ["absolute-time"]})

>>> dateparser.parse('23', languages=['de'], settings={"STRICT_PARSING": True})

>>> dateparser.parse('23', languages=['de'])
datetime.datetime(2020, 11, 23, 0, 0)
```

**Comment by herleswarna** [comment]
You are right, I was using `0.7.6`. Sorry for the trouble.

**Comment by noviluni** [comment]
Don't worry! It's better if you open a ticket if you detect weird behaviors and you don't find the root cause! :).
