### ISSUE TITLE
Possible to discard the time part from a parsed results?

### ISSUE THREAD

**Issue by sayakpaul** [scrapinghub/dateparser#865]
Hi folks!

Really enjoying using `dateparser`. 

Currently, I have the following requirement - 

`25/12/2018 8:13:39 PM` should be parsed as `2018-12-25` and NOT as `2018-12-25 20:13:39`. Is there anything I could specify to the `settings` parameter while parsing the strings?

**Comment by Gallaecio** [comment]
Have you tried any of the format and date order settings?

**Comment by sayakpaul** [comment]
Possible to provide a sample that I could refer to?

**Comment by Gallaecio** [comment]
You should start by checking out https://dateparser.readthedocs.io/en/latest/settings.html

**Comment by sayakpaul** [comment]
I did try to explore a few settings. But I am not sure which exact ones I could tweak to make it work.

**Comment by noviluni** [comment]
Hi @sayakpaul!

You don't need to use any settings to get this result. `dateparser.parse()` returns a python `datetime` object:

```python
>>> dateparser.parse('25/12/2018 8:13:39 PM')
datetime(2018, 12, 25, 20, 13, 39)
```
So, if you just want the date you can execute `.date()` over the datetime object:

```python
>>> date_obj = dateparser.parse('25/12/2018 8:13:39 PM')
>>> date_obj.date()
datetime.date(2018, 12, 25)
```

or just

```python
>>> dateparser.parse('25/12/2018 8:13:39 PM').date()
datetime.date(2018, 12, 25)
```


Just take into account that `dateparser.parse()` can return a `datetime` or `None` so it's safer to do something like:

```python
>>> def parse_date(date_string):
...    date_obj = dateparser.parse(date_string)
...    if date_obj:
...        return date_obj.date()

>>> parse_date('25/12/2018 8:13:39 PM')
datetime.date(2018, 12, 25)
```

Let me know if this works for you :)

**Comment by sayakpaul** [comment]
Perfect. Thank you so much. Perhaps including one of these examples in the official documentation would be helpful. I apologize in advance if I missed it out. :)
