### ISSUE TITLE
AWS deployment failure from Mac osx

### ISSUE THREAD

**Issue by dxp168** [scrapinghub/dateparser#872]
AWS fails to run, cause _regex.cpython-36m-x86_64-linux-gnu.so is required for the linux.

**Comment by Gallaecio** [comment]
I’m guessing this is related to question https://stackoverflow.com/questions/59438843/how-can-i-import-regex-on-aws-lambda (with no useful answer at the moment).

So, if `regex` can be installed on AWS Lambda it’s out of the scope of Dateparser. If you would like to get Dateparser to work without `regex`, that’s covered by https://github.com/scrapinghub/dateparser/issues/446
