### ISSUE TITLE
AttributeError in timezone_parser.py: get_offset

### ISSUE THREAD

**Issue by adbar** [scrapinghub/dateparser#891]
Hi, a bug has been found by a user in dateparser/timezone_parser.py:

```
in get_offset(tz_obj, regex, repl, replw)
AttributeError: module 'regex' has no attribute 'compile'
```

https://github.com/adbar/trafilatura/issues/56

**Comment by adbar** [comment]
Solved by the user, closing now.

**Comment by talalriaz** [comment]
I have this issue as well. Kindly share the solution

**Comment by adbar** [comment]
Please see this answer: 
https://github.com/adbar/trafilatura/issues/56#issuecomment-786778592
