### ISSUE TITLE
Provide a way to check supported languages

### ISSUE THREAD

**Issue by eliasdorneles** [scrapinghub/dateparser#9]
Suggested on #6 

The idea is to have something like ``dateparser.languages`` that would allow one to check support for a given language.

Right now, there are language specific code in both ``date_parser.py`` and ``freshness_date_parser.py``.
Any thoughts on how we should do that?

**Comment by Allactaga** [comment]
Resolved in https://github.com/scrapinghub/dateparser/pull/26
