### ISSUE TITLE
Please at least indicate python 3 compatibility.

### ISSUE THREAD

**Issue by fake-name** [scrapinghub/dateparser#91]
I am looking for a Python 3 date parsing library, and I actually wound up trying to install this library before realizing it's only Py2k compatible.

If you aren't planning on supporting python 3, can you please at least note that (hopefully rather prominently) somewhere in the readme?

**Comment by Allactaga** [comment]
Hi @fake-name, I am sorry to hear that you've wounded up. For your convenience we've duplicated information about supporting only python 2 (for now) into readme file.

**Comment by fake-name** [comment]
Cool, thanks.
