### ISSUE TITLE
"First of this month" becomes January 

### ISSUE THREAD

**Issue by robertocarta** [scrapinghub/dateparser#947]
Hi, I noticed that anything in the form of "x of this month" returns current datetime:

```
datetime.datetime(2021, 7, 22, 14, 48, 14, 688482)
>>> dateparser.parse("1st of this month")
datetime.datetime(2021, 7, 22, 14, 48, 24, 709477)
>>>
```

However, even more puzzling:
```
>>> dateparser.parse("20th")
datetime.datetime(2021, 7, 20, 0, 0)
>>> dateparser.parse("1st")
datetime.datetime(2021, 1, 22, 0, 0)
>>>
```

**Comment by noviluni** [comment]
Hi @robertocarta, `dateparser` currenly doesn't support ordinals like `1st`, `first` or `20th`. However, it's planned. 

We build the [**number-parser**](https://github.com/scrapinghub/number-parser) with this goal, but it has not yet integrated.

**Comment by noviluni** [comment]
Hi @Gallaecio, I will close this in favor of that issue. Thanks!
