### ISSUE TITLE
dateparser.search.search_dates default order on dates is DMY instead of MDY.

### ISSUE THREAD

**Issue by Jiawei-Han-Vanderbilt-Math** [scrapinghub/dateparser#948]
According to the documentation, the default date order is MDY which translates to month first, day second and year last order. The function dateparser.search.search_dates is not doing so sometime. See below for a concrete example.
![image](https://user-images.githubusercontent.com/33468935/126706808-a17418e0-bcb3-45a1-811a-75c651c2acc5.png)
![image](https://user-images.githubusercontent.com/33468935/126706856-3d3830c6-d106-428f-ab54-6cefb8a7c6e5.png)

**Comment by noviluni** [comment]
Hi @Jiawei-Han-Vanderbilt-Math!

What is hapenning is that the detected language is not English, and the detected locale has their own `DATE_ORDER`, which probably is DMY.

You have different options to get the order you want:

1. Limit the language (useful if you know which language are you going to parse):
```python
>>> search_dates('DATE 11/07/2018', languages=['en'])
[('11/07/2018', datetime.datetime(2018, 11, 7, 0, 0))]
```

2. Set using the default language order to False with the `PREFER_LOCALE_DATE_ORDER` setting:
```python
>>> search_dates('DATE 11/07/2018', settings={'PREFER_LOCALE_DATE_ORDER': False})
[('11/07/2018', datetime.datetime(2018, 11, 7, 0, 0))]
```

I will close the issue, let me know if there's anything that it's not clear enough.

Cheers!
