### ISSUE TITLE
Support for particular chinese date format

### ISSUE THREAD

**Issue by demelziraptor** [scrapinghub/dateparser#95]
![image](https://cloud.githubusercontent.com/assets/977968/8627298/60e42c36-274a-11e5-8b1d-620eea092666.png)

This is on amazon.cn reviews section: http://www.amazon.cn/Logitech-%E7%BD%97%E6%8A%80-M185%E6%97%A0%E7%BA%BF%E5%85%89%E5%AD%A6%E9%BC%A0%E6%A0%87/product-reviews/B00776T3NA/ref=dpx_acr_txt?showViewpoints=1

In unicode this is `u'2012\u5e742\u670825\u65e5'`, and I'm not sure what the characters mean but it looks like you can just remove them and parse the remaining numbers.

**Comment by Allactaga** [comment]
We operate *slightly differently* then "just remove them and parse the remaining numbers" :smiley: 

This particular issue could be solved by adding `u'日'` (which is `u'\u65e5'`) as a translation for a "day". However, google translate tells me that this symbol also could be translated as a "date", so I'd like to hear from someone familiar with a context of this word.

**Comment by waqasshabbir** [comment]
Fixed by PR #142
