### ISSUE TITLE
Assumes day of the month is current day when not given

### ISSUE THREAD

**Issue by lmmx** [scrapinghub/dateparser#970]
It doesn't matter for my use, but upon trying to parse a partial date, it isn't able to identify this:

```py
>>> import dateparser
>>> dateparser.parse("March-April 2021")
>>> dateparser.parse("March 2021")
datetime.datetime(2021, 3, 25, 0, 0)
>>> dateparser.parse("1 March 2021")
datetime.datetime(2021, 3, 1, 0, 0)
>>> dateparser.parse("March 2021")
datetime.datetime(2021, 3, 25, 0, 0)
>>> dateparser.parse("January 2021")
datetime.datetime(2021, 1, 25, 0, 0)
```

- Note: today is the 25th, the parser is assuming that I want the same day for the other months I enter.

It would be better to give 0 for the day perhaps, and then it would be clearly a 'null' value (as no month has a 0th day)

(Also found it was not possible to parse date ranges as shown in the first example)

**Comment by Gallaecio** [comment]
https://dateparser.readthedocs.io/en/latest/settings.html#handling-incomplete-dates
