### ISSUE TITLE
New Regex Release: regex==2021.8.27 breaks dateparser (SegFault)

### ISSUE THREAD

**Issue by AndyXan** [scrapinghub/dateparser#972]
Hello Dateparser Team, 

Long story short - did take some debugging today. But the newly bread regex release breaks dateparser utility. 

`virtualenv -p /usr/bin/python3 ~/.virtualenvs/fresh`
`workon fresh`
`pip install dateparser`

```
pip freeze
backports.zoneinfo==0.2.1
dateparser==1.0.0
python-dateutil==2.8.2
pytz==2021.1
regex==2021.8.27
six==1.16.0
tzlocal==3.0
```

```
Type "help", "copyright", "credits" or "license" for more information.
import dateparser                                                       
dateparser.parse("2020-09-10 14:32:00.100").replace(tzinfo=None) 
Segmentation fault (core dumped)
```

`pip install regex==2020.10.28`

```
import dateparser                                                       
dateparser.parse("2020-09-10 14:32:00.100").replace(tzinfo=None) 
datetime.datetime(2020, 9, 10, 14, 32, 0, 100000)
```

So quickfix: pin regex-version in dateparser dependencies. Long term.. I have no idea what causes this :)

**Comment by athossampayo** [comment]
@noviluni This problem was affecting some deployments were I work, so I made a quick hotfix doing exactly what you said, excluding the problematic version on setup.py. 

Mind to check the PR? Any suggestions are very well received as this is my first PR on regex.
