### ISSUE TITLE
Support timezone in Czech locale ("SELČ")

### ISSUE THREAD

**Issue by tadeoos** [scrapinghub/dateparser#975]
This string is failing to parse: `"16. srpna 2021 9:59:44 SELČ"`.

[According to Google](https://www.google.com/search?q=SEL%C4%8C+time+zone&spell=1&sa=X&ved=2ahUKEwjAk6LWqNvyAhVRLewKHRqfBOMQBSgAegQIARAx&biw=1440&bih=707) _SELČ_ is Central European Summer Time

I received this datetime format in email sent from Apple Mail app with Czech language locale.

**Comment by noviluni** [comment]
It should be quite simple to add it in `dateparser/dateparser/timezones.py` in case you want to do it :)

https://github.com/scrapinghub/dateparser/blob/master/dateparser/timezones.py#L70

**Comment by tadeoos** [comment]
@noviluni thanks for pointing me in the right direction. PR opened :)
