### ISSUE TITLE
Invalid date getting parsed

### ISSUE THREAD

**Issue by csalazar** [scrapinghub/dateparser#98]
Hi guys, the string `u'Wed, 30 Nov -0001 00:00:00 +0000'` is getting parsed to `datetime.datetime(2001, 11, 30, 2, 0)` which is wrong.

**Comment by Allactaga** [comment]
Hm, I believe that this is `dateutil` bug.
```python
>>> from dateutil import parser
>>> parser.parse("Wed, 30 Nov -0001 00:00:00 +0000")
datetime.datetime(2001, 11, 30, 0, 0, tzinfo=tzutc())
```

**Comment by waqasshabbir** [comment]
Related to #66

**Comment by waqasshabbir** [comment]
Hi @csalazar, the problem with above string is, it's structure is perfect. `%a, %d %b -%Y HH:MM:SS Z`. We can introduce some sort of filters to handle problems like this for instance drop the date if it's older than year `1900`.
