### ISSUE TITLE
Add "black" for code formatting?

### ISSUE THREAD

**Issue by kishan3** [scrapinghub/dateparser#983]
Hello Guys,

Should dateparser library be using black for code formatting ?

https://black.readthedocs.io/en/stable/
There is also blue: https://blue.readthedocs.io/en/latest/

**Comment by noviluni** [comment]
Using some code formatters like black or blue help to have a more standarized code, but at the same time can be annoying.

I'm not 100% sure of adding this, but in case we do it, before applying black, we should need a mechanism (pipelines) to ensure that:
* Some selected files use black/blue (and we add more files slowly)
or
* New code uses black/blue formatting
or
* Black/Blue is automatically applied in PRs 

Only after adding one of these mechanism we can start changing the files. Any preference on it?

Also, could you expose advantages/disadvantages of using them, and differences among different alternatives (black, blue, etc)?

Thanks!
