### ISSUE TITLE
Missing encoding in file header leads to crash on python2 for invalid ASCII

### ISSUE THREAD

**Issue by NL66278** [scrapinghub/dateparser#988]
File "/home/openeyedev/var/projects/vwn_hr_deluxe_8011/odoo/eggs/dateparser-1.0.0-py2.7.egg/dateparser/date.py", line 104
SyntaxError: Non-ASCII character '\xd0' in file /home/openeyedev/var/projects/vwn_hr_deluxe_8011/odoo/eggs/dateparser-1.0.0-py2.7.egg/dateparser/date.py on line 104, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

This is a line that wants to remove a Russian character from the date.
```
104     date_string = RE_SANITIZE_RUSSIAN.sub(r'\1 ', date_string)  # remove 'г.' (Russian for year) but not in words
```

**Comment by lopuhin** [comment]
hi @NL66278 currently dateparser requires at least python 3.5, and python 2 is not supported.

**Comment by NL66278** [comment]
@lopuhin What is the last release of dateparser to support python 2? Unfortunately I have some customers stuck on this...

**Comment by lopuhin** [comment]
@NL66278 it was `0.7.6`

**Comment by NL66278** [comment]
@lopuhin Thank you for the information. I will use this to pin the version.
