### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kagrawal2** [scrapinghub/dateparser#989]
Would it be possible to get a new tagged release of this library? There have been some important commits in the last year such as the thread safety fix that would be great to have rather than pulling from the master branch.

**Comment by Gallaecio** [comment]
Wow, I did _not_ realize it had been almost a year already.

**Comment by kagrawal2** [comment]
thanks @Gallaecio :)

**Comment by Gallaecio** [comment]
No problem. It was really @noviluni, though :)
