### ISSUE TITLE
How to use dateparser to detect dates

### ISSUE THREAD

**Issue by bokstaller** [scrapinghub/dateparser#991]
I have a short question. In the introduction it is stated that I should only input the date to the parser.
But is it somehow possible to use dateparser in such a way that I give it a sentence that can potentially contain a date, like a detection?

Thanks in advance

**Comment by lopuhin** [comment]
hi @bokstaller 

>  is it somehow possible to use dateparser in such a way that I give it a sentence that can potentially contain a date, like a detection?

Yes - this is the purpose of ``search_dates`` function, see https://dateparser.readthedocs.io/en/latest/?badge=latest#search-for-dates-in-longer-chunks-of-text
