### ISSUE TITLE
`dateparser.parse` detects a date where there isn't

### ISSUE THREAD

**Issue by angel-langdon** [scrapinghub/dateparser#992]
Given the below example:

```python
>>> import dateparser
>>> dateparser.parse("on:")
datetime.datetime(2021, 9, 29, 0, 0)
```

This does not make any sense.

**Comment by Gallaecio** [comment]
It may make sense in some language.

Does it happen if you pass the language of the source text? It does not happen for English:

```
>>> import dateparser
>>> dateparser.parse("on:")
datetime.datetime(2021, 9, 29, 0, 0)
>>> dateparser.parse("on:", languages=["en"])
>>> 
```

**Comment by angel-langdon** [comment]
> Does it happen if you pass the language of the source text? 
I don't know because I have to use the library with multiple languages.

BTW, in what language does "on:" make sense to be "2021-09-29" ? 🤣

**Comment by Gallaecio** [comment]
I don’t want to look into it unless I have to, but in some language `on` could mean (e.g. be a short form for) “the day before yesterday”.

**Comment by Gallaecio** [comment]
> I have to use the library with multiple languages.

Does it need to support every language on the planet? You can pass a list of languages to Dateparser, you don’t need to pass a single language.

**Comment by angel-langdon** [comment]
> Does it need to support every language on the planet? 

Yes I can, thank you very much!

> I don’t want to look into it unless I have to, but in some language on could mean (e.g. be a short form for) “the day before yesterday”.

So it's a feature not a bug! I understand, thank you very much!
